### ISSUE TITLE
add samples for iterableSubjectChangers to api-fluent and api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1038]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
See ArraySubjectChangerSamples in api-fluent and ArraySubjectChangerSamples in api-infix, we want similar samples for iterableSubjectChangers.kt

- [ ] create IterableSubjectChangerSamples in api-fluent
- [ ] add asListFeature and asList (see first two methods in ArraySubjectTransformationSamples in api-fluent)
- [ ] add `@sample` tag to the functions in iterableSubjectChangers.kt
- [ ] create IterableSubjectChangerSamples in api-infix
- [ ] add asListFeature and asList (see first two methods in ArraySubjectTransformationSamples in api-infix)
- [ ] add `@sample` tag to the functions in iterableSubjectChangers.kt

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by simonNozaki** [comment]
Please close this
