### ISSUE TITLE
add samples for ListFeatureExtractorSamples to api-fluent and api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1045]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
See ListFeatureExtractorSamples in api-fluent and ListFeatureExtractorSamples in api-infix, we want similar samples for iterableSubjectChangers.kt

- [ ] create ListFeatureExtractorSamples in api-fluent
- [ ] add function `getFeature` for the first function/overload of `get` in listFeatureExtractors.kt (see CollectionFeatureExtractorSamples..sizeFeature as a guideline)
- [ ] add function `get` for the second overload of `get` in listFeatureExtractors.kt (see CollectionFeatureExtractorSamples as a guideline)
- [ ] add `@sample` tag to the functions in listFeatureExtractors.kt
- [ ] create ListFeatureExtractorSamples in api-infix
- [ ] add function `getFeature` for the first function/overload of `get` in listFeatureExtractors.kt (see CollectionFeatureExtractorSamples..sizeFeature as a guideline)
- [ ] add function `get` for the second overload of `get` in listFeatureExtractors.kt (see CollectionFeatureExtractorSamples as a guideline)
- [ ] add `@sample` tag to the functions in listFeatureExtractors.kt

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by simonNozaki** [comment]
At #1129 , thanks to introduce query, I'll work on this.

**Comment by robstoll** [comment]
@simonNozaki see todos in issue description. They describe step by step what you need to do. Does that help?

**Comment by simonNozaki** [comment]
> @simonNozaki see todos in issue description. They describe step by step what you need to do. Does that help?

Sorry so much, I missed the description of issue. I can maybe do this by todos with step by step .

**Comment by simonNozaki** [comment]
Hi, @robstoll .

Again seeing projects, it seems that ListFeatureExtractorSamples already exists in `ch.tutteli.atrium.api.infix.en_GB.samples` and `ch.tutteli.atrium.api.fluent.en_GB.samples`.

And these class has both `getFeature` and `both`, so I think this issue can be closed because of sample codes.

**Comment by robstoll** [comment]
You're right, sorry about that. Looks like I already added it and forgot to close the issue. Take a look at #1038 this one is still open

**Comment by simonNozaki** [comment]
@robstoll 

Oh, great, I see!. So, please assign me to #1038. I'm ready to add samples for `iterableSubjectChangers`!
