### ISSUE TITLE
shorcut for Path.exists and Path.existsNot

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#108]
*Platform* (JVM, JS and/or Android): jdk8

## Code related feature
```
expect(Paths.get("xyz")).exists()
expect(Paths.get("nonExisting").existsNot()
//instead of
expect(Paths.get("xyz")).feature(Files::exists, arrayOf()) { toBe(true) }
expect(Paths.get("xyz")).feature(Files::notExists, arrayOf()) { toBe(true) }
```

*domain*
- extend PathAssertions with `existsNot` (`exists` is already provided)
- modify PathAssertionsBuilder, delegate to pathAssertions (as for `exists`)
- delegate implementation to robstoll-lib in PathAssertionsImpl (as for `exists`)

*lib*
- implement _exists and _existsNot (I have already setup a dependency to niok which provides Path.exists)

*api*
- add  `existsNot` (`exists` is already provided)
- extend PathAssertionsSpec in specs-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
I'll work on this
