### ISSUE TITLE
shortcut for Path. isReadable and isWritable

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#112]
*Platform* (JVM, JS and/or Android): jdk8

## Code related feature
```
expect(Paths.get("xyz")).isReadable()
expect(Paths.get("xyz")).isWritable()
//instead of
expect(Paths.get("xyz")).feature(Files::isReadable) { toBe(true) }
expect(Paths.get("xyz")).feature(Files::isWritable) { toBe(true) }
```
Following the things you need to do:

*domain*
- extend PathAssertions with `isReadable` and `isWritable` (as for `exists`)
- modify PathAssertionsBuilder, delegate to pathAssertions (as for `exists`)
- delegate implementation to robstoll-lib in PathAssertionsImpl (as for `exists`)

*lib*
- implement _isReadable and _isWritable in pathAssertions.kt in robstoll-lib (I have already setup a dependency to niok which provides Path.isReadable and Path.isWritable) => see _exists as example, better use a descriptive Assertion instead of creating a feature assertion, less noisy, more readable, I would use `DescriptionBasic.IS` as description.

*api*
- add  `isReadable` and `isWritable` (`exists` as guideline)  and `@since 0.9.0` (adopt to current version) to the KDOC
- extend PathAssertionsSpec in specs-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
It feels odd to have `isWritable`, `isRedable`, but not `isExecutable`, since those are the tree POSIX file permissions.

**Comment by jGleitz** [comment]
Note: I am planning to have the assertions do more than just being mere shortcuts. I would also like to have them report whether a file existed at all.

**Comment by robstoll** [comment]
I included it myself first but as I never had a test where this was required, I excluded it again. Thus I would suggest you ask yourself the same question, do you have a test where you need it? If not, I wouldn't add it yet and wait until someone requires it. However, I will not reject a PR if you want to include it in any case.

Concerning additional checks, thats perfectly fine with me. But please do not add additional assertions use a descriptive assertion with a failure hint instead.

**Comment by jGleitz** [comment]
I see your point. I do not have a concrete use case in mind, it just seemed reasonable to say “c” when we are saying “a” and “b”

**Comment by jGleitz** [comment]
See #111 for an update on my progress.
