### ISSUE TITLE
add tests for reportOptions to MapToContainInOrderOnlyKeyValueExpectationsSpec

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1129]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature

Following the things you need to do:

- [ ] see TODOs in MapToContainInOrderOnlyKeyValueExpectationsSpec 

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by simonNozaki** [comment]
Hi @robstoll ,

I'll work on this. I'm new to open source projects, so would you support me where to start?

**Comment by robstoll** [comment]
@simonNozaki sure, I guess you had already a look at [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution). Note that adding a sample would probably be an easier issue to start with and as you are new, I recommend you work on one of those:
https://github.com/robstoll/atrium/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sample

**Comment by simonNozaki** [comment]
@robstoll 
Thank you for your replying!

>  Note that adding a sample would probably be an easier issue to start with and as you are new
Yes, so I'll work on this:
https://github.com/robstoll/atrium/issues/1045

**Comment by simonNozaki** [comment]
@robstoll ,
Thanks to assign me to this issue. Can I add some methods or utilities to the base class of `MapToContainInOrderOnlyKeyValueExpectationsSpec` , `MapLikeToContainFormatSpecBase` ?

`IterableToContainSpecBase` (the base class of `IterableToContainInOrderOnlyValuesExpectationsSpec`) has those, so I suppose that it's better to match its example.

**Comment by robstoll** [comment]
Sure go ahead

**Comment by simonNozaki** [comment]
Hi, @robstoll 

I wrote the first spec in `context`, so how can I run specs? In locally, thgrough gradle,  I ran `./gradlew :atrium-specs:jvmTest --info`, but it seems that gradle could not look up test cases.

Though I checked `wiki` of this, repository, but I could not found the way to run.

**Comment by robstoll** [comment]
@simonNozaki specs only defines the spexs in a parametric way. It's the tests of the Api you need to run in the end. easiest is you run ./gradlew build. If you want to be more specific, then run ./gradle :atrium-api-fluent-en_GB:test or :jvmTest

**Comment by robstoll** [comment]
@simonNozaki let me know in case you need help

**Comment by simonNozaki** [comment]
Sorry, in these days i was so busy in my company, so I could not commit to this issue...

**Comment by robstoll** [comment]
@simonNozaki no worries and no hurry, just wanted to be sure you are not stuck
