### ISSUE TITLE
rewrite readme-examples/build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1159]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Would be nicer to have the build file in Kotlin instead of groovy

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Chandra-Sekhar-Bala** [comment]
Hey, @robstoll I'll work on this :)

**Comment by Chandra-Sekhar-Bala** [comment]
So, to be specific I need to replace "build.gradle" with "build.gradle.kts"  in the README.MD file right @robstoll  ?

**Comment by robstoll** [comment]
No, you task is to rewrite https://github.com/robstoll/atrium/blob/main/misc/tools/readme-examples/build.gradle (i e. currently groovy based) to build.gradle.kts (Kotlin based)

**Comment by Chandra-Sekhar-Bala** [comment]
Well I haven't worked on groovy yet. Can you please provide some resource to get this work done?

**Comment by robstoll** [comment]
@Chandra-Sekhar-Bala I suggest you read https://kotlinlang.org/docs/multiplatform-add-dependencies.html and similar sites and compare groovy and Kotlin.

**Comment by robstoll** [comment]
@Chandra-Sekhar-Bala do you need help?

**Comment by Kaustubh-Umbarkar** [comment]
I'll do this

**Comment by DakshSuryavanshi** [comment]
hello @robstoll I would like to work on this issue if it's still open.

**Comment by DakshSuryavanshi** [comment]
hello @robstoll just needed a confirmation, you basically want is that to change the extension of the file and solve the errors.
and finally convert groovy to kotlin.

**Comment by robstoll** [comment]
@DakshSuryavanshiyou got it right. solving errors and migrate from groovy to kotlin is the same in this case. I don't think you need to read a lot of groovy stuff. Change the file extension and see what errors remain, the IDE will help you as well.

**Comment by jakubriegel** [comment]
@DakshSuryavanshi are you still working on that? If not, I can take it

**Comment by robstoll** [comment]
@jakubriegel IMO you can start with this, @DakshSuryavanshi can still try to come up with a PR on their own for learning purposes

**Comment by jakubriegel** [comment]
Cool 🚀 I'll make a PR in 2-3 days
