### ISSUE TITLE
Migrate Spek1 specs to Spek2

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#116]
*Platform* (jvm, jdk8, js, android): jvm

## Test-Code related issue
We have not yet migrated all specs to spek2.
Following a list modules in which there are still spek1 specs
- atrium-core-robstoll-lib-jvm
- atrium-domain-robstoll-lib-jvm

Search for `import org.jetbrains.spek.api.Spek`and for `TODO #116` to find those specs

*TODO*:
- copy the spec from misc/atrium-spec to misc/specs/atrium-specs-common or move it
  from misc/atrium-specs-jvm to misc/atrium-specs-common
 
- migrate the spec, which most of the time involves:
  - search for `import org.jetbrains.spek.api.Spek` replace with `import org.spekframework.spek2.Spek`
  - search for `import org.jetbrains.spek.api.include` replace with `import ch.tutteli.atrium.specs.include`
  - search for `import ch.tutteli.atrium.verbs.internal.AssertionVerbFactory` replace with `import ch.tutteli.atrium.api.verbs.internal.AssertionVerbFactory`
  - search for `import ch.tutteli.atrium.spec.` replace with `import ch.tutteli.atrium.specs`
  - search for `test(` replace with `it(`
  - search for `group(` replace with `context(`
  - search for `on(` repalce with `context(`
  - search for `verbs.checkImmediately` replace with `verbs.check`
  - rewrite `describeFun` => see https://github.com/robstoll/atrium/pull/209/files#diff-676c33efc276af1070bfde5d55307d9dR23
  - plus some further adjustments like import `describe`

See https://spekframework.org/migration/ for additional hints on the topic

## Your first contribution?
- Write a comment `I'll work on ...` if you would like to migrate one of the specs 
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by monst12** [comment]
Hey @robstoll, I would love working on this.

**Comment by robstoll** [comment]
@monst12 nice :+1: I suggest you start off by migrating one spek and create a PR for it before you move on to the next one.

**Comment by robstoll** [comment]
@monst12 do you still work on this issue?

**Comment by assaflei** [comment]
Hi @robstoll I would like to work on this issue, how do you suggest I should get started?

**Comment by robstoll** [comment]
Hi @assaflei 

How about you start with the following (all very similar):
- bundles/fluent-en_GB/atrium-fluent-en_GB-jvm/src/test/kotlin/custom/SmokeSpec.kt
- bundles/fluent-en_GB/extensions/atrium-fluent-en_GB-smoke-test-kotlin_1_3/src/test/kotlin/custom/SmokeSpec.kt
- bundles/fluent-en_GB/extensions/atrium-fluent-en_GB-smoke-test-jdk8/src/test/kotlin/custom/SmokeSpec.kt

Those should be very easy (not much more than changing the import I guess but you will see).
After those you could continue with (a second PR):
core/robstoll-lib/atrium-core-robstoll-lib-jvm/src/test/kotlin/ch/tutteli/atrium/core/robstoll/lib/reporting/DetailedObjectFormatterSpec.kt

The following commit shows what was necessary to migrate DelegatingAssertionCheckerSpec which is probably similar:
https://github.com/robstoll/atrium/pull/209/files

Also have a look at the hints in the description of this issue. Let me know in case you need more help

**Comment by robstoll** [comment]
All necessary specs have been migrated, closing this. Follow up for moving things will follow
