### ISSUE TITLE
rewrite misc/tools/atrium-samples-test/build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1161]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Would be nicer to have the build file in Kotlin instead of groovy

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Procrasteenator** [comment]
Hi, I would like to work on this issue but I am a beginner and haven't worked on writing Gradle files before, it would be great if you could guide me. 
Thank You

**Comment by robstoll** [comment]
@Procrasteenator maybe not the best issue to start with in this case. Take a look at 1046. 
If you want to continue with this one, then read https://kotlinlang.org/docs/multiplatform-add-dependencies.html and similar sites and compare groovy and Kotlin.

**Comment by agataporwit** [comment]
I have some Kotlin experience and would like to challange myself. Would that be a good place to start ? I am open to any suggestions.

**Comment by robstoll** [comment]
@agataporwit give it a go, you will quickly find out if your list or not I guess. Ask if you need help 🙂

**Comment by robstoll** [comment]
@agataporwit There is already a PR for this issue by @stexxe which I just merged. 
I hope you have not yet started with your work. In case you have, then you might be interested to compare your work with that of stexxe's see https://github.com/robstoll/atrium/pull/1163
There are still other good first issues:
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by Stexxe** [comment]
I'll work on this
