### ISSUE TITLE
Option to describe the subject

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#120]
Any Platform.

## Code related feature
```kotlin
val file = …
readAllLines(file).forEachIndexed { lineIndex, line ->
	expect(line)
		.describedAs("$file @${lineIndex + 1}")
		.containsNot(…)
}
```

this is something that is possible in AssertJ and I haven’t found a way to do this with Atrium. Sometimes, we have relevant information about the subject that is not present in its #toString. Like in the case above, where we can describe the exact offending line.

Admittedly, I do not need this very often. But when I do, it is because the data Atrium prints is not sufficient to quickly find the error. I would like to have a way to provide the description myself.

There already exists [CommonFields#representationProvider](https://github.com/robstoll/atrium/blob/master/core/api/atrium-core-api-common/src/main/kotlin/ch/tutteli/atrium/creating/AssertionPlantWithCommonFields.kt#L44), which seems to be doing what I would like to do, but I found no method to change it.

**Comment by robstoll** [comment]
There are numerous ways to achieve what you want but they are not yet exposed to the API level as I am not yet sure how I want to expose them. 
If your code really looks like the above and you don't want fail fast behaviour, then I recommend to have a look at the [Data-Driven Testing](https://github.com/robstoll/atrium#data-driven-testing) section in the readme.

Some questions to better understand your use cases:
- do you want to show `"$file @${lineIndex + 1}"` only in case of a failure?
- do you still want to see what line was or are you not interested in that at all?

**Comment by jGleitz** [comment]
> do you want to show `"$file @${lineIndex + 1}"` only in case of a failure?

The way I have written this specific example, I will only see output for failing lines. For my purpose, this is fine (there are many lines, so I would not want to have output about the other lines in case of a failure).

However, in general, I think the feature I am asking for would apply to whenever the subject is described in the output, whether for a failure or not.

> do you still want to see what line was or are you not interested in that at all?

If it is possible, I would like to see the line content (so maybe the “normal” description), together with the additional info. However, this is not a hard requirement.

> do you have a public repo where I can see the use cases?

I have not pushed the particular piece of code this example comes from anywhere yet (and i. And I do not have another example at hand, currently. As I said, I think this is not a use case that comes up very often, however, when it does, adding more description would be very helpful.

Here is the full test case this example comes from:

```kotlin
@Test
fun `does not reference the source classes`() {
    val tmpdir = getEmptyTestOutputFolder("metamodel-generator-test")
    MetaModelCodeGenerator("io.metamodel.test", BuildingsMetamodel)
        .generateBlocking(tmpdir)
    val forbiddenPackages = BuildingsMetamodel.interfaces.map { it::class.java.`package`.name }.distinct()
    walk(tmpdir)
        .filter { isRegularFile(it) }
        .forEach { file ->
            readAllLines(file).forEachIndexed { lineIndex, line ->
                expect(line)
                    /*.describedAs("$file @${lineIndex + 1}")*/
                    .containsNot(forbiddenPackages.first(), *forbiddenPackages.drop(1).toTypedArray())
            }
        }
}
```

This test looks at generated code and makes sure that certain packages are not mentioned anywhere in it. Because there are many files and they contain a lot of lines, it is helpful to have the file and line printed in the error message, so that we can investigate manually.

> If your code really looks like the above and you don't want fail-fast behaviour, then I recommend to have a look at the Data-Driven Testing section in the readme.

I am not sure I understand your hint here. I _do_ want fail-fast behaviour (and the code above gives me that). Also, I read through Data-Driven Testing and could no find anything that fit my use case.

**Comment by robstoll** [comment]
Sorry I was not clear enough. Say you have multiple lines which contain a forbidden package. Do you want to stop at the first line (your implementation is perfect) or would you want to see all failures?
I'll write up an example how you can add additional information when having a keyboard in front of me and not my phone.

One follow up question. I could also augment charsequence.containsNot with a failure hint showing the line + position of matches. Would that be appreciated? Mayve even turn your request redundant?

**Comment by jGleitz** [comment]
> Say you have multiple lines which contain a forbidden package. Do you want to stop at the first line (your implementation is perfect) or would you want to see all failures?

Ah, now I get it. You are right, having _all_ errors reported instead of just the first one would be even better (I am not used to this even being a possibility because I come from JUnit + Hamcrest).

> I could also augment charsequence.containsNot with a failure hint showing the line + position of matches.

> Would that be appreciated?

It would definitely be helpful.

> Maybe even turn your request redundant?

Yes and no. I still would need to know which file contains the offending line. In my case, I could get away with using parameterized tests for that. But a) would the code be a little more complicated and b) I still believe that there is a general use case here, even though it is not occurring very often.

**Comment by robstoll** [comment]
I try to keep the API as small as possible because more is not always better. I'll think about it though. I am finishing up 0.9.0 so it will most likely make it into 0.10.0 where I will add easier ways to add failure hints and additional information to assertions.

In the meantime you can use functionality from the domain level => `AssertImpl` is kind of the entry point to the domain. Notice though, that domain (or core) are not stable yet and it could be that I break things in a future version. I'll usually deprecate things and add migrations but sometimes its not possible. 
Following two ideas which hopefully cover your requirements (see also [Define Single Assertions or Assertion Groups](https://github.com/robstoll/atrium#define-single-assertions-or-assertion-groups)):

In case you want to see all failures within a file:
```
@Test
fun `does not reference the source classes`() {
    //...
    expect(file) { // an assertion group block reports all failures and does not stop at the first failure
        readAllLines(file).forEachIndexed { lineIndex, line ->
            AssertImpl.feature.property(this, { line }, Untranslatable("line: $lineIndex + 1"))
                .containsNot(forbiddenPackages.first(), *forbiddenPackages.drop(1).toTypedArray())
        }
    }
}
```
Or in case you want to see all files with forbidden packages and all failures in the files:
```
@Test
fun `does not reference the source classes`() {
    expect("no file contains a forbidden package") {
        val tmpdir = getEmptyTestOutputFolder("metamodel-generator-test")
        MetaModelCodeGenerator("io.metamodel.test", BuildingsMetamodel)
            .generateBlocking(tmpdir)
        val forbiddenPackages = BuildingsMetamodel.interfaces.map { it::class.java.`package`.name }.distinct()
        walk(tmpdir)
            .filter { isRegularFile(it) }
            .forEach { file ->
                AssertImpl.feature.property(this, { file }, Untranslatable("file $file")) { //also an assertion group block reporting all failures
                    readAllLines(file).forEachIndexed { lineIndex, line ->
                        AssertImpl.feature.property(this, { line }, Untranslatable("line: $lineIndex + 1"))
                            .containsNot(forbiddenPackages.first(), *forbiddenPackages.drop(1).toTypedArray())
                    }
                }
            }
    }
}
```

**Comment by jGleitz** [comment]
Thanks a lot for pointing out how to achieve this currently!

Bonus karma points for showing me how I can improve my test logic :+1:!

When I look at the code you provided, it seems to me like it would make a lot of sense to add the feature I am asking for as an optional parameter to the expect and property calls. Together with named parameters, I think this could look nice:

```kotlin
expect(subjectVariable, description = "My additional Info") { … }
```

or, here: 
```kotlin
feature({line}, description = "line: $lineIndex + 1") { … }
```

(such a feature method taking a lambda does not exist yet in the API, though)

I fully understand that you do not want to add features unnecessarily. From my point of view, It would bring value for situations where test logic is inherently more complex. I also feel that the feature would have low maintenance overhead because, as you have shown, the functionality already exists in the (well modelled!) domain logic. But this is of course a decision you as maintainer must make.

**Comment by robstoll** [comment]
a method `feature` will be added in 0.9.0, usually meant for features of the subject (replacement for `property` and `returnValueOf`) but can also be used for cases as the above one by providing a custom feature description:
```
feature("My additional Info") { line }
```

**Comment by jGleitz** [comment]
> a method feature will be added in 0.9.0, usually meant for features of the subject (replacement for property and returnValueOf) but can also be used for cases as the above one by providing a custom feature description

This is great!
To be honest, I think this fulfils my use case in most cases. It would still be nice to be able to do the same thing on `expect`, but having it on `feature` is already very helpful.

So I think this ticket boils down to: should `expect` get the same functionality that `feature` already has, namely adding a description to the subject?

**Comment by jGleitz** [comment]
The remainder of this issue is covered in https://github.com/robstoll/atrium/issues/153
