### ISSUE TITLE
migrate StringFormatTest from spek to kotest

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1200]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
We want to move away from spek as it's future regarding maintenance and development is quite unsure. 
As I don't want to loose hierarchical test setup I decided that we go with kotest

Following the things you need to do:

- [ ] add dependency for the js paltform to kotest in misc/atrium-specs/build.gradle.kts (if not there yet)
- [ ] rewrite atrium-core/src/jsTest/kotlin/ch/tutteli/atrium/core/polyfills/StringFormatTest.kt to kotest extending a [DescribeSpec](https://kotest.io/docs/framework/testing-styles.html#describe-spec)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Dark-Knight11** [comment]
I'll work on this

**Comment by robstoll** [comment]
we are using kotlin.test here, nothing to migrate. Sorry for the confusion
