### ISSUE TITLE
Update gradle in sample projects

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1206]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Update the gradle wrapper in /samples/... projects.

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jakubriegel** [comment]
@robstoll Gradle is on the newest `7.5.1` version in all of sample projects:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip
```
Did you mean to update it all the other projects?

**Comment by jakubriegel** [comment]
Gradle releases page: https://gradle.org/releases/

**Comment by robstoll** [comment]
Oh really. Sorry about that then
