### ISSUE TITLE
include jdk11 and jdk12 in CI

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#124]
*Platform* jvm, jdk8

This project is tested on Java 8 and 9 in CI. But [Java 9 is not supported anymore](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html). So it might make sense to always test on Java 8 and the most recent version of Java instead.

## Non-Code related feature
**Is your feature request related to a problem? Please describe.**
Related to [niok not being compilable with Java 9](https://github.com/robstoll/niok/issues/6)

**Describe the solution you'd like**
Always test compiling with Java 8 (for backwards compatibility) and the most recent version of Java.

**Describe alternatives you've considered**
Fix the dependencies, stick to testing on Java 9 (but I would not know why).

**Comment by robstoll** [comment]
Its actually tested on 8, 9 (travis - linux) and 9, 10 (appveyor - windows). I agree that we should include 11 and 12. Let's do the following: 
travis: 8, 11 => both LTS versions of Java
appveyor: 9, 10, 12 => STS versions of Java

I am not only after LTS versions as long as the STS don't give us headaches. So far they didn't so let's continue this way.
