### ISSUE TITLE
Stop using Gradle’s junit-platform-plugin, migrate to builtin plugin instead

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#126]
## Non-Code related feature
The project executes tests using the deprecated `junit-platform` gradle plugin. By using gradle’s builtin JUnit support, we would get:

 * a lot less warnings in CI
 * a better CLI output
 * IntelliJ integration

![atrium-gradle-test-intellij](https://user-images.githubusercontent.com/4305652/63732676-a666e200-c875-11e9-8d98-70d8cb06bf3d.png)

**Describe the solution you'd like**
Update [tutteli-gradle-plugins](https://github.com/robstoll/tutteli-gradle-plugins) to use builtin JUnit support.

**Comment by robstoll** [comment]
@jGleitz released v0.28.0 tutteli-gradle-plugins

**Comment by jGleitz** [comment]
@robstoll We have another Java compatibility issue, see https://ci.appveyor.com/project/robstoll/atrium/builds/27018228/job/f9d885v3982t1mu3

Can you re-release the plugins, but compiled with Java 8 (or 9?)

**Comment by robstoll** [comment]
Hm... I see, I need to include a check into the release-process. I will release a fix lster this afternoon.
