### ISSUE TITLE
Artifact name in Bintray's jCenter repository

### ISSUE THREAD

**Issue by ddmytrenko** [robstoll/atrium#13]
Can you please fix the artifact names on your Bintray?  

*Affected Version*:    `0.4.0` and newer

It was "`atrium-api`" before. But today I had to spent some time to figure
out why Gradle cannot find `'ch.tutteli:atrium-api:0.6.0'` dependency

Best regards!

Thanks for the lib!

**Comment by robstoll** [comment]
@ddmytrenko Thanks for your feedback, I introduced multiple APIs starting with 0.4.0: https://github.com/robstoll/atrium/releases/tag/v0.4.0

I was not even aware of that someone is using an older versions, good to know :)
You have the choice, either depend on a bundle module:
```gradle
dependencies {
    testCompile "ch.tutteli:atrium-cc-en_UK-robstoll:$atrium_version"
}
```
which internally defines the remaining dependencies (see https://github.com/robstoll/atrium/blob/master/bundles/atrium-cc-en_UK-robstoll/build.gradle for furhter information)
or you can define all dependencies on your own (see also the above build.gradle for an example).
Also notice that you can choose between the pure fluent api (same API as in 0.3.0) or an infix api, where you would need to depend on the followoing bundle:
```gradle
dependencies {
    testCompile "ch.tutteli:atrium-cc-infix-en_UK-robstoll:$atrium_version"
}
```

**Comment by robstoll** [comment]
I guess the problem is solved with the above comment. If not or you need further informatin, then please let me know it by adding an additional comment

**Comment by ddmytrenko** [comment]
@robstoll 
Thanks, yeah the "problem" is solved ;)
It was my bad. I did not mention that change.
