### ISSUE TITLE
elementsOf(Iterable) for CharSequence.contains

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#130]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
```
val iterable : Iterable<Any> = listOf('h', "ello", 2019)
expect("hello world 2019").contains.exactly(1).elementsOf(iterable)

//instead of

expect("hello world 2019").contains.exactly(1).elementsOf(iterable.first(), *iterable.drop(1).toTypedArray())
```

Following the things you need to do  (see also a0b539c0 for a guideline):

*api*
- add fun `elementsOf` in apis/fluent-en_GB/atrium-fluent_en_GB-common/../charSequenceContainsCreators.kt (see other functions there)
  - it is enough if you delegate to `values`
  - `require` that the `Iterable.hasNext`
  - and `@since 0.9.0` (adopt to current version) to the KDOC
- extend CharSequenceContainsAtLeastAssertionsSpec (see TODO)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by RenatoViana01** [comment]
I'll work on this

**Comment by robstoll** [comment]
@RenatoViana01 do you need any help?

**Comment by robstoll** [comment]
@RenatoViana01 un-assign you so that others can take over.

**Comment by mattyway** [comment]
I'll work on this
