### ISSUE TITLE
shortcut Iterable.containsExactlyElementsOf

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#131]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
```
expect(listOf(1, 2)).containsExactlyElementsOf(anotherList)

//instead of

expect(listOf(1, 2)).contains.inOrder.only.elementsOf(anotherList)
```

Please react with :+1:  in case you would like to see this shortcut implemented. The more upvotes the more likely I will implement it myself. You are of course welcome to implement it yourself and create a PR. Write `I'll work on it` as comment so that we can assign the task to you.

**Comment by robstoll** [comment]
@audkar do you mind sharing your use case for this functionality?

**Comment by audkar** [comment]
For me this is probably one of the most often used checks on collections. I have tests which assert that all UI states changed in right order after some events were emitted. e.g.
```
expect(recordedStates).containsExactlyElementsOf(listOf(Idle, IsLoading, ErrorShown))
```

**Comment by robstoll** [comment]
Are you aware of that you can write the above as:
```
expect(recordedStates).containsExactly(Idle, IsLoading, ErrorShown)
```
I guess the list is somewhat dynamic right?

**Comment by audkar** [comment]
Actually no. Was using Google's `Truth` before and was not expecting that `containsExactly` is checking order :)
So for my usecase `ElementsOf` part is not necessary then :)))

**Comment by robstoll** [comment]
I see, Atrium follows AssertJ's behaviour here (see [api diff - iterable contains](https://github.com/robstoll/atrium/blob/master/apis/differences.md#iterable-contains) for a compact view of Iterable contains features).

 Good to have a Truth user here, let me know if you miss a feature in Atrium by opening an issue

**Comment by tkech17** [comment]
i saw this topic, and i tought is was not active anymore(from comments).
if it's still active assign me
