### ISSUE TITLE
add JVM kotest sample project

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1325]
- [ ] Add a sample how one can use Atrium in combination with kotest under samples/jvm/kotest
- [ ] include sample in misc/tools/atrium-samples-test/settings.gradle and in misc/tools/atrium-samples-test/build.gradle.kts

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by tanbirali** [comment]
I will work on this

**Comment by ReccaFlames** [comment]
Hello @robstoll Is this issue still available? If it is, I will work on this
