### ISSUE TITLE
Add Expect<Map<K, V>>.values -> Expect<Collection<Map.Entry<K, V>> feature extractor

### ISSUE THREAD

**Issue by vlsi** [robstoll/atrium#1356]
## Code related feature

```kotlin
val map = mapOf("a" to 1, "b" to 2")

expect(map) {
  entries.toHaveElementsAndAll { ... }
}
```

There are

```
val <V, T : Map<*, V>> Expect<T>.values: Expect<Collection<V>>

val <K, T : Map<out K, *>> Expect<T>.keys: Expect<Set<K>>
```

However, there is no `.entries` property.

I see there is `asEntries()`, however, it is not clear why the names are inconsistent.

**Comment by robstoll** [comment]
we use `as...` to transform the subject without it being reported (in contrast to a feature extraction). you can still use `its { entries }` if you like. 
Do you actually want to see the transformation?

**Comment by vlsi** [comment]
I do not want to see the transformation.
I was searching the way to add expectations for map entries, and it was surprising why `keys` and `values` were there, and `entries` was missing.

I'm not sure if enforcing `as...` convention for non-reported extractors is good or bad, however, it would probably make sense to document those naming conventions so the users could understand the common theme.

However, I think the use of non-reported `.values` for Map would not be surprising for the users.

**Comment by robstoll** [comment]
> I'm not sure if enforcing as... convention for non-reported extractors is good or bad,

Me neither actually. In case you have time,  take a look at https://github.com/robstoll/atrium-roadmap/issues/44
