### ISSUE TITLE
toHaveElementsAndAll + feature produces non-grouped output

### ISSUE THREAD

**Issue by vlsi** [robstoll/atrium#1357]
### Affected Version

0.18.0

### API

fluent-en_GB

### Platform

jvm

### Kotlin Version

1.8

### How to reproduce the problem?

```kotlin
expect(listOf(Throwable("hello"))) {
    toHaveElementsAndAll {
        message.toContain("world")
    }
}
```

### Describe the bug

There seem to be several issues:
1) `message:` branch is duplicated in the output.
2) I don't understand why "to be an instance of type" appears
3) It looks like **the value** for "message" is not displayed

```
I expected subject: [java.lang.Throwable: hello]        (java.util.Collections.SingletonList <1506951181>)
◆ elements need all: 
    » ▶ message: 
        ◾ to be an instance of type: String (kotlin.String) -- Class: java.lang.String
    » ▶ message: 
        ◾ to contain: 
          ⚬ value: "world"        <207471778>
              » but no match was found
    ❗❗ following elements were mismatched: 
       ⚬ index 0: kotlin.Throwable
```

### Expected behaviour

I think `to be an instance of type` should not be displayed, and, in case it is displayed, it should be rendered under a common `message:` group like in

```
I expected subject: [java.lang.Throwable: hello]        (java.util.Collections.SingletonList <1506951181>)
◆ elements need all: 
    » ▶ message: hello <-- value should be here
        ◾ to be an instance of type: String (kotlin.String) -- Class: java.lang.String
        ◾ to contain: 
          ⚬ value: "world"        <207471778>
              » but no match was found
    ❗❗ following elements were mismatched: 
       ⚬ index 0: kotlin.Throwable
```

----

This looks much better:

```kotlin
expect(AbstractMap.SimpleEntry("a", Throwable("hello"))) {
    value.message.toContain("world")
}
```

=>

```
I expected subject: a=java.lang.Throwable: hello        (java.util.AbstractMap.SimpleEntry <1301987508>)
◆ ▶ value: kotlin.Throwable
    ◾ ▶ message: "hello"        <408069119>
        ◾ to contain: 
          ⚬ value: "world"        <1912850431>
              » but no match was found
```

**Comment by vlsi** [comment]
if I use `message {...}`, the output is better: `message:` is properly grouped in the report

```kotlin
expect(listOf(Throwable("hello"))) {
    toHaveElementsAndAll {
        message {
            toContain("world")
        }
    }
}
```

=>

```
I expected subject: [java.lang.Throwable: hello]        (java.util.Collections.SingletonList <1131592118>)
◆ elements need all: 
    » ▶ message: 
        ◾ to be an instance of type: String (kotlin.String) -- Class: java.lang.String
        ◾ to contain: 
          ⚬ value: "world"        <908084672>
              » but no match was found
    ❗❗ following elements were mismatched: 
       ⚬ index 0: kotlin.Throwable
```

**Comment by vlsi** [comment]
`to be an instance of type:` comes from `notToEqualNull()`:

```kotlin
val <T : Throwable> Expect<T>.message: Expect<String>
    get() = feature(Throwable::message).notToEqualNull()
...
inline fun <reified T : Any> Expect<T?>.notToEqualNull(): Expect<T> =
    notToEqualNullButToBeAnInstanceOf(T::class).transform()
```

**Comment by robstoll** [comment]
Thanks for your report. I see most things you have already figured out yourself. 
For the notToEqualNull topic, please take a look at  https://github.com/robstoll/atrium/issues/330 and state your wishes there.

For:
>  » ▶ message: hello <-- value should be here

the  » bullet point signifies an explanation of an expectation. `hello` should not be shown there as there could be multiple mismatches. But it should show up in the mismatch part. I.e. here:
```
⚬ index 0: kotlin.Throwable
    ▶ message: "hello"
```    
I thought I already created an issue but apparently I only had it in my head.
Created a new issue: https://github.com/robstoll/atrium/issues/1360
please state your wishes/thoughts there.

Regarding the grouping. We could already improve the implementation whenever the fail fast syntax is used within an expectation group. But I am not entirely sure we should or rather we should define in which cases we do it. I think it would make sense if the feature appears in sequence (as in your example). However, I wouldn't do it in the following case
```
expect { throwableFunction }.toThrow<MyException> {
   message.startsWith("expected prefix")
   cause.toEqual(null)
   message.toContain("foo bar")
}
```
I guess there is a reason why one chooses to split it this way. i.e. in reporting I would show:
```
> message 
  * to start with: "expected prefix"
> cause: 
  * not to equal: null
> message 
  * to contain: "foo bar" 
```

**Comment by robstoll** [comment]
closing this as it entails multiple different aspects which are all covered in other issues:
> There seem to be several issues:
> 1) `message:` branch is duplicated in the output.
> 2) I don't understand why "to be an instance of type" appears
> 3) It looks like **the value** for "message" is not displayed

1. #805 
2. was improved with #330 
3. #1359
