### ISSUE TITLE
Use spek2 for DeprecationTestEngine 

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#136]
## Code related feature
Currently we are using Spek1 internally of DeprecationTestEngine and in the long run we should switch to spek2 also here.

see ReadmeTestEngine for an example, few things have changed.
Note also that: 
- catching Throwables during discovery is no longer required if we pass `--fail-if-no-test` to the ConsoleLauncher. See readme-examples/build.gradle for guidance.
- forgiving a test is now done via a customListener (see ReadmeTestEngine.runSpekWithCustomListener) and no longer with a `ForgivingTest`

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Megamiun** [comment]
Hello, what should be put at the name of the SpekEngineDescriptor on the case of DiscoveryFailed?

**Comment by robstoll** [comment]
@Megamiun I guess you plan to change the `try-catch` in the `discover` fun. Right? Otherwise I don't know what your question is. We do no longer require the try-catch (see ReadmeTestEngine) and instead we can pass `--fail-if-no-tests` to the ConsoleLauncher (see build.gradle in atrium-bc-test

**Comment by robstoll** [comment]
we had to split it up into DeprecationSpek1TestEngine and DeprecationSpek2TestEngine (49fe394).
Once we have migrated all spek1 to spek2 we can get rid of DeprecationSpek1TestEngine. In this sense this issue is resolved
