### ISSUE TITLE
show why there was a mismatch

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1360]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```kotlin
expect(listOf(person1, person2, ...)).toHaveElementsAndAll { 
  age.toBeGreaterThanOrEqual(18) 
  zip.notToEqual(null)
  city.notToEqual(null)
}
```

in reporting we see currently
```
I expected subject: [Person(..), Person(...)]
◆ elements need all: 
    » age
      » to be greater than or equal: 18
    » zip
      » not to equal: null
    »  city 
      » not to equal: null
    ❗❗ following elements were mismatched: 
       ⚬ index 0: Person(...)
       ⚬ index 1: Person(...)
```

Depending on the representation of Person it is possible to see why it mismatches but it is cumbersome as one has to manually scan the output and see why it failed. I would like to see all failing assertions per mismatch:
```
I expected subject: [Person(..), Person(...)]
◆ elements need all: 
    » age
      » to be greater than or equal: 18
    » zip
      » not to equal: null
    »  city 
      » not to equal: null
    ❗❗ following elements were mismatched: 
       ⚬ index 0: Person(...)
          > age: 10
            * to be greater than or equal: 18
       ⚬ index 1: Person(...)
          > city: null
            * not to equal: null
```

This closely relates to #724 and I think we should also provide a report option which allows to define if we show also successful assertions or not

**Comment by vlsi** [comment]
I think you just duplicated https://github.com/robstoll/atrium/issues/1359

**Comment by robstoll** [comment]
Haha... 10min difference, I should have written faster :D 
Going to merge the two :+1:
