### ISSUE TITLE
Commit Size & Frequency

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#141]
The [contributing guidelines](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md) state:

 > your pull request should ideally consist of one small commit. If not then make sure: 
> -  it cannot be split up in several pull requests.
 > - your commits are meaningful to others - e.g. do not include temporary commits like before lunch; Squash commits where appropriate.

I am not sure how to interpret this. If we look at #140, for example, I have pushed small patch commits. I think they have advantages:
 - reviewers can better see what has changed since their last review
 - I can see which commits have which effects on CI
 - I do not have to force push, which is helpful should others have pulled the branch

I agree with the “it cannot be split up in several pull requests” part. But I want to suggest we drop the “should ideally consist of one small commit” part. Instead, we can allow arbitrarily sized commits (they still should have meaningful messages, though) and squash on merge. What do you think?

**Comment by jGleitz** [comment]
Note that I started #140 with one big commit, but that is also not what I normally do. Normally, I would have pushed my progress commit by commit.

**Comment by robstoll** [comment]
Fine with me, can you please write up a PR with the corresponding changes?

**Comment by jGleitz** [comment]
I see your intention. I see three different cases and would handle them as follows:

 1. The pull request consists of a small number of meaningful commits -> merge normally
 1. The pull request consists of small commits and is not very large -> squash merge
 1. The pull request is large and/or there are commits that we would like to keep separate -> ask the author to do an interactive rebase and squash appropriately.

The point is that I expect most PRs to fall in the first or second category.

**Comment by robstoll** [comment]
I expect the same. Thanks for the PR resolving this issue.
