### ISSUE TITLE
Add feature extractors for SQLException

### ISSUE THREAD

**Issue by vlsi** [robstoll/atrium#1421]
*Platform* (all, jvm, js): jvm
*Extension* (none, kotlin 1.3): none

## Code related feature
```kotlin
import java.sql.SQLException

val Expect<SQLException>.errorCode: FeatureExpect<SQLException, Int>
    get() = feature("errorCode", SQLException::getErrorCode)

fun Expect<SQLException>.errorCode(assertionCreator: Expect<Int>.() -> Unit) =
    feature("errorCode", SQLException::getErrorCode, assertionCreator)

val Expect<SQLException>.sqlState: FeatureExpect<SQLException, String>
    get() = feature("sqlCode", SQLException::getSQLState)

fun Expect<SQLException>.sqlState(assertionCreator: Expect<String>.() -> Unit) =
    feature("sqlCode", SQLException::getSQLState, assertionCreator)
```

I wonder if that can be autogenerated with something like https://github.com/robstoll/atrium/issues/1358 when building Atrium.
Apparently, it does not make sense for everybody to re-generate the extractors, however, it might be nice if the accessors like that could be auto-generated in Atrium.

**Comment by robstoll** [comment]
I don't see a reason why we cannot generate it but until we have #1358 someone could already start and implement it manually (including samples etc.) :slightly_smiling_face:

**Comment by rafiya2003** [comment]
can I work on this?

**Comment by robstoll** [comment]
sure, let me know in case you need more info in the description (you can also take a look at older good first issues.

**Comment by robstoll** [comment]
@rafiya2003 do you need help?

**Comment by rafiya2003** [comment]
yes

**Comment by robstoll** [comment]
what help do you need? have you started with something?

**Comment by BereKanters** [comment]
Hey, can I work on this?

**Comment by robstoll** [comment]
@BereKanters sure are you still working in the other one (build matrix)? Otherwise unasign please
