### ISSUE TITLE
Library lacks support for IR compiler

### ISSUE THREAD

**Issue by mdahm** [robstoll/atrium#1481]
### Affected Version

1.0.0

### API

fluent

### Platform

js

### Kotlin Version

1.8.22

### How to reproduce the problem?

```gradle
 js(IR) {
    browser() {
      testTask {
        useKarma {
          useChromeHeadless()
          // Otherwise:
          // enabled = false
        }
      }

      commonWebpackConfig {
        this.outputFileName = "protokolle-webpack.js"
//mode = KotlinWebpackConfig.Mode.DEVELOPMENT
        cssSupport {
          enabled.set(true)
        }
      }
    }

    generateTypeScriptDefinitions()
    binaries.executable()
  }
```

### Describe the bug

* What went wrong:
Could not determine the dependencies of task ':protokolle:jsTestPackageJson'.
> Could not resolve all dependencies for configuration ':protokolle:jsTestNpm'.
   > Could not resolve ch.tutteli.atrium:atrium-fluent:1.0.0.
     Required by:
         project :protokolle
      > No matching variant of ch.tutteli.atrium:atrium-fluent:1.0.0 was found. The consumer was configured to find a library for use during 'kotlin-runtime', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:
          - Variant 'jsApiElements-published' capability ch.tutteli.atrium:atrium-fluent:1.0.0 declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
              - Incompatible because this component declares a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.js.compiler' with value 'legacy' and the consumer needed a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir'
              - Other compatible attributes:
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'jsRuntimeElements-published' capability ch.tutteli.atrium:atrium-fluent:1.0.0 declares a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.js.compiler' with value 'legacy' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir'
              - Other compatible attributes:
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'jvmApiElements-published' capability ch.tutteli.atrium:atrium-fluent:1.0.0:
              - Incompatible because this component declares a component for use during compile-time, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attributes:
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'jvmRuntimeElements-published' capability ch.tutteli.atrium:atrium-fluent:1.0.0 declares a component for use during runtime:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attributes:
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'metadataApiElements-published' capability ch.tutteli.atrium:atrium-fluent:1.0.0:
              - Incompatible because this component declares a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a component for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attributes:
                  - Doesn't say anything about its component category (required a library)
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')

* Try:

### Expected behaviour

New IR format should be supported...

**Comment by robstoll** [comment]
Thanks for the report :+1:

**Comment by robstoll** [comment]
We will switch to IR with the drop of Kotlin 1.2 and 1.3, Atrium 1.1.0 will require Kotlin 1.4 and only support IR

**Comment by robstoll** [comment]
@mdahm v1.1.0-IR-alpha is out: https://github.com/robstoll/atrium/releases/tag/v1.1.0-IR-alpha

Let me know in case it doesn't work for you. I keep this issue open for the moment so that others see it was well
