### ISSUE TITLE
Explanatory Assertion in Failure Hint Swallowed if not in Group

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#150]
*Affected Version*: 0.9.0-alpha
*Platform* (jvm, jdk8, js, android): all

## How to reproduce the problem  
Consider the following test:
```kotlin
describe("assertion formatting") {
    it("prints the explanation") {
        fun Expect<*>.testAssertion() {
            addAssertion(
                ExpectImpl.builder.descriptive.failing
                    .withFailureHintBasedOnDefinedSubject(this) {
                        ExpectImpl.builder.explanatory.withExplanation("I want to be seen!").build()
                    }
                    .withDescriptionAndRepresentation("test", "assertion")
                    .build()
            )
        }

        expect {
            expect("foo").testAssertion()
        }.toThrow<AssertionError> {
            messageContains("I want to be seen!")
        }
    }
}
```

Output:
```
expect the thrown exception: ch.tutteli.atrium.reporting.AtriumError
◆ ▶ message: "assert: "foo"        <1554237100>
◆ test: "assertion"        <288586319>"        <735356373>
    ◾ contains: 
      ⚬ value: "I want to be seen!"        <1248526148>
        ⚬ ▶ number of occurrences: 0
            ◾ is at least: 1

```

## Describe the bug
From my intuition _and_ the relevant documentation, I would expect the above test case to pass. Instead, the explanatory assertion in the failure hint is not printed.

The documentation of `ExplanatoryAssertion` states (only):

> is typically used in an [AssertionGroup]

It works if the explanatory assertion is wrapped in an assertion group, however, it is not intuitive that a group is required _and_ it creates an unnecessary intendation. This test case passes:

```kotlin
describe("assertion formatting") {
    it("prints the explanation") {
        fun Expect<*>.testAssertion() {
            addAssertion(
                ExpectImpl.builder.descriptive.failing
                    .withFailureHintBasedOnDefinedSubject(this) {
                        ExpectImpl.builder.explanatoryGroup.withDefaultType.withAssertion(
                            ExpectImpl.builder.explanatory.withExplanation("I want to be seen!").build()
                        ).build()
                    }
                    .withDescriptionAndRepresentation("test", "assertion")
                    .build()
            )
        }

        expect {
            expect("foo").testAssertion()
        }.toThrow<AssertionError> {
            messageContains("I want to be seen!")
        }
    }
}
```

**Comment by robstoll** [comment]
good catch, I guess the second test would fail as well if you had not wrapped it into an explanatory group.

**Comment by jGleitz** [comment]
This bug led to an architectural discussion which is done in https://github.com/robstoll/atrium-roadmap/issues/1.

**Comment by robstoll** [comment]
(4660067 has nothing to do with this issue. unfortunately I used the wrong number)

**Comment by robstoll** [comment]
I will not change the behaviour of ExplanatoryAssertion but improve the KDoc, due to the architectural decisions taken in https://github.com/robstoll/atrium-roadmap/issues/1

The AssertionBuilder has already stated the necessary context:
``` 
/**
 * Builder to [...] -- has to be a child of an [ExplanatoryGroup] (see [explanatoryGroup]).
 */
val explanatory: Explanatory.ExplanationOption
```

**Comment by jGleitz** [comment]
@robstoll: Please be aware that this decision introduces some inflexibility, which I experience in #140: I create Assertions of which I do not know yet whether they will be shown alone or in a group. Having to work around this is possible, but also somewhat awkward.

Semantically speaking, it makes sense from my point of view to have an `ExplanatoryAssertion` that is not in a `ExplanatoryGroup`: It is just some piece of explanation.

**Comment by robstoll** [comment]
For this we have RepresentationOnlyAssertion now

**Comment by jGleitz** [comment]
Yes, but this is the inflexibility I am talking about: When creating the assertion, I have to already know whether the Assertion will end up in an `ExplanatoryGroup` or not. I would like to write code where this is only decided at a later point.

What is your intended semantic difference between an `ExplanatoryAssertion` and a `RepresentationOnlyAssertion`? Why can we not just use a `RepresentationOnlyAssertion` in a `ExplanatoryGroup`?

**Comment by robstoll** [comment]
ExplanatoryAssertion will be made obsolete once we have Reportable. RepresentationOnlyAssertion can of course also be used within an ExplanatoryAssertion (as all other assertions).

**Comment by jGleitz** [comment]
Ah, now I get what you are planning. Makes total sense. Thanks!
