### ISSUE TITLE
add samples for BigDecimal expectation functions in api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1505]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
We already have samples in ch.tutteli.atrium.api.fluent.en_GB.samples.BigDecimalExpectationSamples but only cover `expect toEqual ...` in api-infix. We want to cover the rest of the functions as well.

**TODO:**
- make sure every function in apis/infix/atrium-api-infix/src/jvmMain/kotlin/ch/tutteli/atrium/api/infix/en_GB/bigDecimalExpectations.kt which is not deprecated has a corresponding sample in ch.tutteli.atrium.api.infix.en_GB.samples.BigDecimalExpectationSamples and links to it => see toEqual in bigDecimalExpectations.kt for an already implemented case (and take a look at ch.tutteli.atrium.api.fluent.en_GB.samples.BigDecimalExpectationSamples as guidance for the samples, make sure you use the infix api though.)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by VarunEnishetty** [comment]
Hi @robstoll , I would like to work on this issue.
Can you please assign this task to me and also help me with any changes to considered?

**Comment by robstoll** [comment]
@VarunEnishetty the description should still fit, let me know if you have questions

**Comment by VarunEnishetty** [comment]
@robstoll , can you please look into this PR - https://github.com/robstoll/atrium/pull/1513
