### ISSUE TITLE
restrict E in Expect<Optional<E>>.toBePresent to `: Any`

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1509]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature

Following the things you need to do:

*logic*
- [ ] restrict E of OptionalAssertions.isPresent accordingly

*api-fluent*
- [ ] adjust `toBePresent` in apis/fluent/atrium-api-fluent/src/jvmMain/kotlin/ch/tutteli/atrium/api/fluent/en_GB/optionalExpectations.kt

*api-infix*
- [ ] adjust `toBe present` in apis/infix/atrium-api-infix/src/jvmMain/kotlin/ch/tutteli/atrium/api/infix/en_GB/optionalExpectations.kt

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Nikos-Tsiougranas** [comment]
Hello @robstoll! I would like to work on this.
