### ISSUE TITLE
samples for CharSequence.toContain.atMost

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1517]
## Code related feature

Following the things you need to do:

*api-fluent*
- [ ] add a `atMost` method in CharSequenceToContainCheckerSamples 
- [ ] link in the KDoc of the corresponding function in charSequenceToContainCheckers.kt to the sample via `@sample` (see atleast)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Nikos-Tsiougranas** [comment]
I will work on this!
