### ISSUE TITLE
allow to change the representation of the subject

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#153]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
```
expect(listOf(1, 22, 3 /* imagine way more numbers */, representation="xy numbers")
  ...
```
would result in reporting:
```
expect: xy numbers
* ...
```
the feature is intended for single cases where the representation is too verbose.

See https://github.com/robstoll/atrium-roadmap/issues/18 for the initial (and ongoing) discussion.

A way to change the reporting for a certain type can already be achieved via custom ObjectFormatter. We will simplify the way to exchange the ObjectFormatter for a single `expect` with another issue.

**Comment by robstoll** [comment]
implemented by 5ab8f78

**Comment by matejdro** [comment]
It looks like this was removed by https://github.com/robstoll/atrium/commit/55c3ce0a07e3df9232f7bca5f10ae1f3390d75a7?

**Comment by robstoll** [comment]
Good catch. That's correct, we realised that default arguments causes trouble. 
We change to the following for now but it's experimental (you need to enable it via compiler flag):
```
expect(listOf(1, 22, 3 /* imagine way more numbers */)
  .withOptions(textRepresentation="xy numbers")
```

But... I just saw that this was only activated for internal assertion verbs => #362

**Comment by matejdro** [comment]
Isn't that syntax a bit too verbose? Maybe `withDescription` would be better?

**Comment by robstoll** [comment]
Thanks for your input, it's experimental so yes, we can definitely discuss about it. 
First a word to the naming in atrium:
```
expect: 1
* to be: 2   (kotlin.Int<123>)
```
`to be` is the description, `2   (kotlin.Int<123>)` is the representation. 
It is up to the user if he wants to use `withOptions("xy numbers")` or `withOptions(textRepresentation="xy numbers")` but maybe `withOptions("xy numbers")` is actually a bad idea and something else would be better.
Maybe `withTextRepresentation("xy numbers")` instead? I am using `Text` as you can also define something like `list.filter { it % 2 == 0}` as representation.
Thoughts?

**Comment by robstoll** [comment]
I have opened an issue in atrium-roadmap, let us continue the discussion there
