### ISSUE TITLE
samples for CharSequence.toContain... in api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1543]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature

we already have corresponding samples in api-fluent, the goal is to copy the following examples to api-infix and transform them to the infix style:
- apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/CharSequenceToContainCheckerSamples.kt
- apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/CharSequenceToContainCreatorSamples.kt
- apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/CharSequenceToContainSearchBehaviourSamples.kt

TODOs:
- copy the above files
- transform them to the infix style
- link from the corresponding functions in the KDOC via `@sample` (see api-fluent for examples)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by robstoll** [comment]
@Nikos-Tsiougranas write a comment if you want to tackle it and I'll assign it to you

**Comment by rohitverma007** [comment]
May I work on this? [and potentially few other related ones]

**Comment by robstoll** [comment]
Sure, I suggest you transform one method in CharSequenceToContainCheckerSamples and then create a draft PR so that I can already give you feedback before you continue with the rest.

**Comment by rohitverma007** [comment]
@robstoll ah ok, created a draft PR for CharSequenceToContainCheckerSamples, let me know how it looks. I will do maybe another one or so and leave the rest.

**Comment by robstoll** [comment]
Looks all good :+1: 
Just to avoid confusion, you can tackle all TODOs of this issue. Just leave the other issues for other people. If no one should be interested until end of October, then I am happily coming back to you as I can need your help. And in the meantime, I could also need help for other issues :slightly_smiling_face: 
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by rohitverma007** [comment]
@robstoll sounds good will wrap this one up soon and then see if I can tackle some other less easy issues from before.
(also happy to work on  other related ones by November if they aren't picked up by then :))

**Comment by BereKanters** [comment]
Hey, I wouldnt mind working on this if nobody is currently assigned.
