### ISSUE TITLE
samples for Iterable.toContain.atLeast

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1545]
## Code related feature

Following the things you need to do:

*api-infix*
- [ ] add a `atLeast` method in IterableLikeToContainCheckerSamples (see CharSequenceToContainCheckerSamples
- [ ] link in the KDoc of the corresponding function in iterableLikeToContainCheckers.kt to the sample via `@sample` (see charsequenceToContainCheckers.kt)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by fergbaldo** [comment]
I'll work on this. 
I'll start looking over how I can achieve this tomorrow and communicate if I have any issues or misunderstanding. Can I please be assigned to work on this? Thanks!

**Comment by fergbaldo** [comment]
Hi, just an update to let you know that I had to delay my first look at this contribution due to some personal issues but I should get a chance to either today or tomorrow. Thanks for the assignment

**Comment by robstoll** [comment]
no stress :)

**Comment by fergbaldo** [comment]
Hi @robstoll, I just uploaded a pull request for a possible solution to this issue. 
Please review this and let me know if any changes need to be made. If no changes are required, then I can likely complete another couple of similar issues today.
