### ISSUE TITLE
introduce Text as replacement for RawString

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#155]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
- introduce Text as replacement for RawString.create which expects String
- treat Translatable always as RawString (adjust DetailedObjectFormatter)
- deprecate RawString and provide ReplaceWith
- replace usages via provided ReplaceWith

**Comment by JithendraD** [comment]
@robstoll hey can I work on this?

**Comment by robstoll** [comment]
@JithendraD This is planned for the next version and not the one we are currently working on. I can ping you once we are working on 0.10.0 if you like

**Comment by robstoll** [comment]
@JithendraD you could start working on this one if you like
