### ISSUE TITLE
samples for Iterable.toContain....elementsOf 

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1554]
## Code related feature

Following the things you need to do:

*api-fluent*
- [ ] add a `elementsOf` method in IterableLikeToContainInAnyOrderCreatorSamples for CharSequence.toContain.inAnyOrder.only.elementsOf(...) 
- [ ] add a `elementsOf` method in IterableLikeToContainInAnyOrderOnlyCreatorSamples for CharSequence.toContain.inAnyOrder.elementsOf(...) 
- [ ] add a `elementsOf` method in IterableLikeToContainInOrderOnlyCreatorSamples for CharSequence.toContain.inOrder.only.elementsOf(...
- [ ] link in the KDoc of the corresponding function in iterableLikeToContain...Creators.kt to the samples via @sample (see charSequenceToContainCreators.kt)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by robstoll** [comment]
@udit5656 do you need help?

**Comment by udit5656** [comment]
Wasn't this issue solved in #1652 ?

**Comment by robstoll** [comment]
@udit5656 thanks for the hint, looks like I forgot to link the PR with this issue, sorry about that
