### ISSUE TITLE
samples for Iterable feature extractors

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#1569]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
*api-fluent*
*api-fluent*
- [ ] add a `minFeature` method in IterableFeatureExtractorSamples for expect(iterable).min()
- [ ] add a `min` method IterableFeatureExtractorSamples for expect(iterable).min { } (i.e. the overload with the assertionCreator-lambda)
- [ ] add a `maxFeature` method in IterableFeatureExtractorSamples for expect(iterable).max()
- [ ] add a `max` method IterableFeatureExtractorSamples for expect(iterable).max { } (i.e. the overload with the assertionCreator-lambda)
- [ ] link in the KDoc of the corresponding function in iterableLikeToContain...Creators.kt to the samples via @sample (see charSequenceToContainCreators.kt)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/main/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by constantine-zubrilin** [comment]
Can I take it?
