### ISSUE TITLE
Iterable.hasNext

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#158]
*Platform* (jvm, jdk8, js, android):

## Code related feature
```
expect(iterable).hasNext()

//instead of

expect(iterable).feature{ f(it::hasNext) }.toBe(true)
```
However, in reporting we want to see:
```
expect: iterable
* has: a next element
```
And not
```
expect: iterable
* hasNext: false
   * to be: true
```

Following the things you need to do:

*domain*
- extend IterableAssertions with a function `hasNext` (see CollectionAssertions.isEmpty as a guideline)
- modify IterableAssertionsBuilder, delegate to iterableAssertions (see CollectionAssertionsBuilder as a guideline)
- delegate implementation to robstoll-lib in IterableAssertionsImpl (see CollectionAssertionsImpl as a guideline)

*lib*
- implement _hasNext in iterableAssertions by using a custom descriptive assertion (see _isEmpty in collectionAssertions.kt)
  - add `HAS("has")` to DescriptionBasic in en_GB
  - add `HAS("hat")` to DescriptionBasic in de_CH

*api*
- provide a fun `hasNext` in iterableAssertions (see collectionAssertions.kt -> isEmpty as a guideline)
- create a new IterableAssertionsSpec in specs-common (see for instance CollectionAssertionsSpec) and extend it in atrium-api-fluent-en_GB-common/src/test

**Bonus**
implement also `hasNotNext()` which looks as follows in reporting:
```
expect: iterable
* has not: a next element
```

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over.
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by sanatik** [comment]
I'll work on this

**Comment by robstoll** [comment]
@sanatik in case you already work on this, I have improved the reporting and adopted the description accordingly
