### ISSUE TITLE
compile android class files into dex bytecode

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#167]
*Platform* (jvm, jdk8, js, android): android

## Code related feature
Currently we don't have a proof that the class files are actually compatible with d8. 
It would be nice if we could compile the resulting class files of a build of an `-android` module with the d8 dexer.

TODO:
- [ ] create a gradle task `checkDexer` (based on JavaExec) for all android projects => do that in the build.gradle in the root -> use `configure(getAndroidProjects()){...}`. The task shall convert all class files to dex-files using the d8 dexer
- [ ] make sure `check` depends on the new task and make sure it is run after `compileKotlin` (use dependsOn)

Some additional hints (the rest needs to be researched):
- docu on how JavaExec works https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html
- dependency to r8 which includes d8 is described here https://mvnrepository.com/artifact/com.android.tools/r8/1.6.84 (not sure in which repositories it is published)
- repo of r8, probably contains further information on how to use it: https://r8.googlesource.com/r8

**Comment by segunfamisa** [comment]
I'll work on this

**Comment by robstoll** [comment]
@segunfamisa do you need help?

**Comment by assaflei** [comment]
I'll try taking this
