### ISSUE TITLE
Path.extension

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#169]
*Platform* (jvm, jdk8, js, android): jdk8

## Code related feature
```
expect(Paths.get("my.txt")).extension.toBe("txt")
expect(Paths.get("my.txt")).extension {
    ...
}

// instead of (assuming one uses Niok)

expect(Paths.get("a/my.txt")).feature { f(it::extension) }.toBe("text")
expect(Paths.get("a/my.txt")).feature({ f(it::extension) }) {
    ...
}
```

Following the things you need to do:

*domain*
- extend PathAssertions with a function `extension` (see other functions as a guideline)
- modify PathAssertionsBuilder, delegate to pathAssertions (see other functions as a guideline)
- delegate implementation to robstoll-lib in PathAssertionsImpl (see other functions as a guideline)

*lib*
- implement _extension in pathAssertions by using the `ExpectImpl.feature.manual` (see collectionAssertions -> _size)
  => you can use `extension` from niok
  - you might have to introduce DescriptionPathAssertion in translations-en_GB and translations_de_CH
  - add `EXTENSION("extension")` to DescriptionPathAssertions for en_GB
  - add `EXTENSION("Dateiendung")` to DescriptionPathAssertions for de_CH

*api* (fluent-en_GB/extensions/jdk8)
- provide a val which returns Expect<String> (see collectionAssertions.kt -> size as a guideline)
- provide a fun which expects an `assertionCreator`-lambda and returns Expect<T> (see collectionAssertions.kt -> size as a guideline)
- extend or write a separate Spec named PathFeatureAssertionsSpec in specs-common (see for instance CollectionFeatureAssertionsSpec) and extend it in atrium-api-fluent-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by lelloman** [comment]
I'll work on this

**Comment by robstoll** [comment]
implemented with https://github.com/robstoll/atrium/commit/9505e97425b7e1ad7ba2dd7e6faed2c090deb260
