### ISSUE TITLE
Path.fileNameWithoutExtension

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#170]
*Platform* (jvm, jdk8, js, android): jdk8

## Code related feature
```
expect(Paths.get("a/my.txt")).fileNameWithoutExtension.toBe("my")
expect(Paths.get("a/my.txt")).fileNameWithoutExtension {
    ...
}

// instead of (assuming one uses Niok, otherwise it is even more verbose)

expect(Paths.get("a/my.txt"))
  .feature("file name without extension") { fileNameWithoutExtension }
  .toBe("my")

expect(Paths.get("a/my.txt"))
    .feature("file name without extension", { fileNameWithoutExtension }) {
        ....
    }
```

Following the things you need to do:

*domain*
- extend PathAssertions with a function `fileNameWithoutExtension` (see other functions as a guideline)
- modify PathAssertionsBuilder, delegate to pathAssertions (see other functions as a guideline)
- delegate implementation to robstoll-lib in PathAssertionsImpl (see other functions as a guideline)

*lib*
- implement _fileNameWithoutExtension in pathAssertions by using the `ExpectImpl.feature.manual` (see collectionAssertions -> _size)
  => you can use `fileNameWithoutExtension` from niok
  - you might have to introduce DescriptionPathAssertion in translations-en_GB and translations_de_CH
  - add `FILE_NAME_WITHOUT_EXTENSION("file name without extension")` to DescriptionPathAssertions for en_GB
  - add `FILE_NAME_WITHOUT_EXTENSION("Dateiname ohne Endung")` to DescriptionPathAssertions for de_CH

*api*
- provide a val which returns Expect<String> (see collectionAssertions.kt -> size as a guideline)
- provide a fun which expects an `assertionCreator`-lambda and returns Expect<T> (see collectionAssertions.kt -> size as a guideline)
- extend or write a separate Spec named PathFeatureAssertionsSpec in specs-common (see for instance CollectionFeatureAssertionsSpec) and extend it in atrium-api-fluent-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by aljacinto** [comment]
Hi @robstoll  I'll work on this

**Comment by aljacinto** [comment]
@robstoll for this one:  provide a val which returns Expect (see collectionAssertions.kt -> size as a guideline) .  Is the below the right place?

```
├── apis
│   └── fluent-en_GB
│       └── extensions
│           └── jdk8
│               └── atrium-api-fluent-en_GB-jdk8-jvm
│                   └── src
│                       └── main
│                           └── kotlin
│                               └── ch
│                                   └── tutteli
│                                       └── atrium
│                                           └── api
│                                               └── fluent
│                                                   └── en_GB
│                                                       └── jdk8
│                                                           └── pathAssertions.kt
```

**Comment by robstoll** [comment]
and the existing function `size` can be found here: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/collectionAssertions.kt

**Comment by aljacinto** [comment]
got it, was basing it on this one:  apis/cc-de_CH/atrium-api-cc-de_CH-common/src/main/kotlin/ch/tutteli/atrium/api/cc/de_CH/collectionAssertions.kt which looks different

**Comment by aljacinto** [comment]
should the PathFeatureAssertionsSpec be in atrium-api-fluent-en_GB-jvm instead of atrium-api-fluent-en_GB-common? because it's only for Path objects?

**Comment by robstoll** [comment]
As it is part of the jdk8 extension it should be next to ch.tutteli.atrium.api.fluent.en_GB.jdk8.PathAssertionsSpec
The spec as such in specs-common on the other hand needs to into the jvm module, next to ch.tutteli.atrium.specs.integration.PathAssertionsSpec
