### ISSUE TITLE
Iterable.containsNoDuplicates

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#172]
*Platform* (jvm, jdk8, js, android): 

## Code related feature
```
expect(iterable).containsNoDuplicates()
```

<hr/>

Please react with :+1: if you would like to see this feature implemented in Atrium, the more upvotes the more likely I will implement it myself -- feel free to [sponsor me](https://github.com/sponsors/robstoll), that would be a motivation too. 
You are of course welcome to work on this issue. Write `I'll work on it` as comment so that we can assign the task to you.

**Comment by frikit** [comment]
I'll work on it

**Comment by robstoll** [comment]
@frikit as this is your first contribution, I advise:
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).
