### ISSUE TITLE
Support for Intellij Diffing

### ISSUE THREAD

**Issue by dsvoronin** [robstoll/atrium#1797]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Non-Code related feature

Hello 👋🏼 . The only thing I am missing after migration to atrium in my projects is the ability to run IntelliJ Idea Diff view to see what exactly is wrong between expected and actual data.

**Describe the solution you'd like**

Consider adding `<Click to see difference>` link as Google Truth and Junit assert libraries.

Like this: https://github.com/google/truth/issues/277

If it's already possible via some extension point please help me find it

**Describe alternatives you've considered**

Analyzing current diff in output can be challenging:
 - most of the times it's not aligned: for example expected line starts a little bit to the right of actual.
 - subtle difference could be hard to spot

**Comment by dsvoronin** [comment]
Thanks, @vlsi 
Looks like the same issue, right. Couldn't find it, was confused with opentest. 
Let's close this one as duplicate

**Comment by robstoll** [comment]
The issue is also in another project, so no wonder you could not find it. I guess I should migrate the issues in atrium-roadmap to discussions here in atrium at some point (discussions did not yet exists back then). So thanks for opening the issues, others might find it easier.
