### ISSUE TITLE
Any.isNoneOf/isNotIn

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#180]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
```
expect(subject).isNoneOf(a, b, ...)
expect(subject).isNotIn(iterable)

//instead of
expect(subject).notToBe(a).notToBe(b)...
expect(subject).notToBe(iterable.next()).notToBe(iterable.next())...
```
However, reporting should not state multiple `not to be` (in case of a Reporter which shows all assertions) but reflect the intended grouping. 
For instance:
```
expect(1).isNoneOf(1, 2, 3, 1)
```
should result in
```
expect: 1
* is none of:
   - 1
```
As we can see from the example, we don't have to check for unique values, that's the responsibility of the developer. Moreover, we want fail-fast behaviour (thus we don't see the second `1` in reporting).

Following the things you need to do:

*atrium-logic*
- extend AnyAssertions with a function `isNotIn` which expects a `List<T>` (see existing functions as a guideline)
- implement isNotIn in DefaultAnyAssertions use `assertionBuilder.list..`
  - add `IS_NONE_OF("is none of")` to DescriptionAnyAssertion for en_GB
  - add `IS_NONE_OF("ist nicht")` to DescriptionAnyAssertion for de_CH
   => use it for `withDescriptionAndEmptyRepresentation`
  -  map the elements of `List<T>` to an `assertionBuilder.representationOnly` (similar to /domain/robstoll-lib/atrium-domain-robstoll-lib-common/src/main/kotlin/ch/tutteli/atrium/domain/robstoll/lib/creating/iterable/contains/creators/InAnyOrderOnlyAssertionCreator.kt => createExplanatoryGroupForMismatchesEtc) and use them for `withAssertions`

*api-fluent-en_GB*
- provide a fun `isNoneOf` with signature `(T, vararg T)` (see mapAssertions.kt -> contains as a guideline)
  - add `@since 0.9.0` to KDOC
- provide a fun `isNotIn` with signature `Iterable<T>`
  - include a `require` that the `Iterable.iterator.hasNext()` 
  - add `@since 0.9.0` to KDOC
- extend AnyAssertionsSpec in specs-common and extend it in atrium-api-fluent-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by DeMack** [comment]
I'll work on this.

**Comment by piyushmor** [comment]
Hi, is someone working on this, else I will take over

**Comment by piyushmor** [comment]
DeMack, are you working on this? Else, I will start

**Comment by robstoll** [comment]
@DeMack do you need help? un-assining you so that others can take over until I get a response

**Comment by gawarz** [comment]
I'll work on this.

**Comment by robstoll** [comment]
@gawarz let me know in case you need help

**Comment by robstoll** [comment]
@gawarz unassigning you so that others can take over. Just leave a comment here in case you still work on it and I assign you again.

**Comment by Jak-Sidious** [comment]
I'll work on this

**Comment by robstoll** [comment]
@Jak-Sidious I just updated the description

**Comment by robstoll** [comment]
@Jak-Sidious un-assigning you so that others can take over

**Comment by z13z** [comment]
I'll work on this

**Comment by z13z** [comment]
Hello. I won't be able to finish this issue. please unasign me

**Comment by anesabml** [comment]
@robstoll can I work on this?
