### ISSUE TITLE
Array.asList instead of asIterable

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#183]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
Currently we provide an `asIterable` for the different Array types. Yet, it would make more sense if we provide an `asList` so that one gets functionality such as `get(index)` as well.

Following the things you need to do:

*api* fluent-en_GB:
- change the functions in /apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/arrayAssertions.kt
  - rename `asIterable` to `asList` 
  - change return type where `Expect<Iterable<E>` is used
  - change parameter type of `assertionCreator`
- rename ArrayAsIterableAssertionsSpec to ArrayAsListAssertionsSpec and adopt the spec accordingly in specs-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by piraces** [comment]
I'll work on this
