### ISSUE TITLE
upgrade spek to 2.0.8 and use spek's `include`

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#193]
*Platform* (jvm, jdk8, js, android): all

## Code related feature
Since Atrium's `include` was pushed back to spek and is included since 2.0.7 we can now use it instead. Thus:
- upgrade spek to 2.0.8
- remove `include` from /misc/specs/atrium-specs-common/src/main/kotlin/ch/tutteli/atrium/specs/SpekExtensions.kt
- add imports for spek's include if required

**Comment by Anubhav007** [comment]
I'll work on it.

**Comment by robstoll** [comment]
I am unsure what your problem is with the last point.It might well be that you don't need to add any import (that's why I wrote `if required`). Try if the project still builds by running `./gr build` (`gr build` in case of windows) in the root of the project. If it does, then you can simply skip step 3.

**Comment by Anubhav007** [comment]
So i tried running the build and there were compilation errors (eg - IterableAnyAssertionsSpec) where **include** is used. For step 1, I updated the **spek2_version = '2.0.8'** in build.gradle line 22.

**Comment by robstoll** [comment]
Could you please push your changes to github and create a PR (prefix the title with [WIP] where WIP stands for work in progress)? This makes review much easier for me

**Comment by robstoll** [comment]
Ah I think I see your problem. Notice that we are currently using Spek 1 in certain modules. You don't have to change these modules. We use spek2 currently in api/fluent-en_GB and extensions as well as in specs-common (specs-jvm etc.). Maybe even some more modules, in short: 
- ignore files which have an `import org.jetbrains.spek.api.Spek`
- only adapt files which have an `import org.spekframework.spek2.Spek`

**Comment by Anubhav007** [comment]
@robstoll I have raised a WIP PR - https://github.com/robstoll/atrium/pull/195 Please let me know what is need to change there.
