### ISSUE TITLE
simplify PathAssertionsSpec fuse describe of similar functions

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#200]
*Platform* (jvm, jdk8, js, android): jdk8

## Code related feature

functions like exists and existsNot form a counterpart of each other. Thus should be reflected in tests IMO and we can also simplify the tests due to this.

Have a look at ch.tutteli.atrium.specs.integration.CharSequenceAssertionsSpec for instance isEmtpy, isNotEmpty => I would like to have the same for exists/existsNot, startsWith/startsNotWith, endsWith/endsNotWith

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by segunfamisa** [comment]
I'll work on this
