### ISSUE TITLE
Use spek-js instead of dummy implementation

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#202]
*Platform* (jvm, jdk8, js, android): 

## Code related feature
We are using Spek to perform multiplatform test. As spek does not JS yet, we used a dummy implementation (just the signatures) so that we still can use Spek for the other platforms. 
This idea was adopted by spek with 2.0.6

Hence we should theoretically be able to use it instead of our dummy implementation. However, it did not work as expected. I have a clue why, your job would be to find out if this is the problem. 

TODO: 
- activate the spek-js dependency in misc/specs/atrium-specs-js/build.gradle
- remove the following folder /misc/specs/atrium-specs-js/src/main/kotlin/org/
- try `./gr build` => I guess it still fails (see https://youtrack.jetbrains.com/issue/KT-33611 for more information)
- ~~turn specs-js into a common-js module (it is currently a UMD module)~~ no longer necessary

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by wudmer** [comment]
@robstoll Hi. I tried to build project but got an error 
`* What went wrong:
Execution failed for task ':atrium-cc-de_CH-robstoll-js:installMocha'.
> Process 'command '/home/wudmer/Documents/atrium/.gradle/npm/npm-v6.4.1/bin/npm'' finished with non-zero exit value 139
`
Is there any known issues with build under linux? I'm use Ubuntu 19.04

**Comment by robstoll** [comment]
Nope, I am using Ubuntu 19.04 myself and it works. Have you tried `./gr clean build` ? Do you use jdk12 by chance, I have only tested it with 11, 9 and 8 on Ubuntu so far.

**Comment by jGleitz** [comment]
I am using Java 12 and have no issues when running `gradle build`.

```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by robstoll** [comment]
@wudmer you can still do the changes and just push them to github and let travis and Github verify if it works. The kotlin issue was updated, as it seems we do no longer have the problem with (probably due to the update of spek to 2.0.7). Hence you can just do the first to points and you are all good.

**Comment by wudmer** [comment]
ok, I'll try it
