### ISSUE TITLE
update tutteli-spek-extensions to 1.0.1

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#218]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature

- update spekExtensions_versions to 1.0.1 in build.gradle in the root
- fix PathAssertionsSpec and PathFeatureAssertionsSpec
- compile the project with `./gr build` to verify that all problems have been addressed

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by ShradhaSangtani** [comment]
I'll work on it
