### ISSUE TITLE
Create a sample project for Atrium + spek

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#219]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

## Code-Documentation related feature
It would be nice if we have a working example similar to the one we created for Atrium + mocha (see samples/js/mocha) but this time for Atrium + spek (so JVM and not JS)
The example project shall show how to setup spek + atrium and include a simple test

This task is a good first issue especially if you intend to set up Atrium + spek anyway

TODO:
- create a module under samples/jvm/spek

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by iamshubh** [comment]
I will work on this!
I want to get started on open source contribution

**Comment by iamshubh** [comment]
@robstoll , kindly assign me again on this

**Comment by robstoll** [comment]
implemented by dccb5c8da6ed165cd3cc4c8f43eb4e5f2653574c
