### ISSUE TITLE
arrayAssertions for the new infix API

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#226]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature

We want to migrate the `api-cc-infix-en_GB...` modules which are based on `Assert` to `Expect`. We have already created the corresponding
modules `api-infix-en_GB...`. Also there are already `fluent-en_GB...` modules where we have already done the transition from `Assert` to `Expect`

Following the things you need to do:

- copy the file `arrayAssertions.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common
  - adjust the signatures of the assertion functions so that they are infix functions (see arrayAssertions.kt in atrium-api-cc-infix-en_GB-common for a guideline)
  - change since 0.9.0 to 0.11.0
- copy the `ArrayAsListAssertionsSpec.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Kshitij09** [comment]
I'll work on this.

**Comment by robstoll** [comment]
@Kshitij09 do you need help?

**Comment by Kshitij09** [comment]
No. Was busy in exams.:sweat_smile: Will work on it now.

**Comment by robstoll** [comment]
@Kshitij09 do you need help now?

**Comment by Kshitij09** [comment]
Actually I'm getting busy in some other stuff. You may unassign me if it has to be implemented urgently. Otherwise, I'll work on it when get the time.

**Comment by robstoll** [comment]
Un-assigning you, so that others can take over. You are welcome to come back and contribute any time (to this or another issue)

**Comment by Kshitij09** [comment]
Sure :+1:

**Comment by isfedorov** [comment]
@robstoll I'll work on this

**Comment by robstoll** [comment]
@isfedorov note that there is a difference between api-fluent and api-cc-infix. cc-infix still provides asIterable where fluent provides asList. Please add `asList` to the new infix api. Moreover, make also the functions which do not expect an assertionCreator `infix` by using the filler object `o` (as for `notToBeNull o` in anyAssertions.kt)
