### ISSUE TITLE
mapAssertions for the new infix API

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#229]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature

We want to migrate the `api-cc-infix-en_GB...` modules which are based on `Assert` to `Expect`. We have already created the corresponding
modules `api-infix-en_GB...`. Also there are already `fluent-en_GB...` modules where we have already done the transition from `Assert` to `Expect`

Following the things you need to do:

- copy the file `mapAssertions.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common
  - adjust the signatures of the assertion functions so that they are infix functions (see mapAssertions.kt in atrium-api-cc-infix-en_GB-common for a guideline)
  - convert the `vararg` functions to two functions, one which expects only one parameter and another which uses a helper object - i.e Pairs and All (see mapAssertions.kt in atrium-api-cc-infix-en_GB-common for a guideline)
  - change since 0.9.0 to 0.10.0
  - convert `isEmpty()` to `toBe Empty` (see mapAssertions.kt in atrium-api-cc-infix-en_GB-common for a guideline)
  - convert `isNotEmpty()` to `notToBe Empty`
- copy the `MapAssertionsSpec.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common
  - introduce a function in the companion object for each assertion function so that we see the infix API in action (see MapAssertionsSpec in atrium-api-cc-infix-en_GB-jvm but use fun1, fun2 etc. to retrieve the name of the function instead of `KFunction<...>` -- use `fun1<..>(...).name`)
- copy the `MapAsEntriesAssertionsSpec.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common
  - introduce a function in the companion object for each assertion function so that we see the infix API in action (see MapAsEntriesAssertionsSpec in atrium-api-cc-infix-en_GB-jvm but use fun1, fun2 etc. to retrieve the name of the function instead of `KFunction<...>` -- use `fun1<..>(...).name`)
- copy the `MapFeatureAssertionsSpec.kt` from atrium-api-fluent-en_GB-common to atrium-api-infix-en_GB-common
  - introduce a function in the companion object for each assertion function so that we see the infix API in action (see MapFeatureAssertionsSpec in atrium-api-cc-infix-en_GB-jvm but use fun1, fun2 etc. to retrieve the name of the function instead of `KFunction<...>` -- use `fun1<..>(...).name`)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by dragid10** [comment]
I can take this one on!

**Comment by robstoll** [comment]
@dragid10 do you need help?

**Comment by dragid10** [comment]
Sorry I haven't had much time to work on it this past week, But I'll reach out tomorrow if I need help!

**Comment by dragid10** [comment]
In trying to fix the Expect.contains function I am unable to use `this contains Pairs(keyValuePair)` while getting the message `Type checking has run into a recursive problem. Easiest workaround: specify types of your  declarations explicitly `

**Comment by robstoll** [comment]
It's always easier for me to see all code to help out with a problem. Can you create a PR please? You can suffix the title of the PR with WIP which stands for work in progress

**Comment by robstoll** [comment]
@dragid10 could you solve your problem?

**Comment by robstoll** [comment]
@dragid10 any progress on this one? do you need help?

**Comment by johnGachihi** [comment]
Hey @robstoll, I am unable to continue contributing for I am quite busy. I will be back when the work load reduces.

**Comment by jlundhol** [comment]
I'm in a small group that will work on this

**Comment by robstoll** [comment]
implemented with 1c5bbb2
