### ISSUE TITLE
remove limit of stacktrace - filtering them should be enough

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#234]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We sometimes show the stracktrace of an exception as Hint for the user, e.g. if a wrong exception is thrown:
```
expect{
  throw IllegalArgumentException("hello")
}.toThrow<AssertionError>()
```

Or if a file cannot be accessed:
```
expect(Paths.get("my.txt")).isReadable()
```

Currently we have hard-coded the max-length of the stacktrace included in the hint (per exception - so a cause with an own stacktrace is shown with the same limit). This could be made configurable. I would imagine that one can define:
- a number > 0 means an exact limit
- a number <= 0  means unlimited

To be discussed: 
- do we want to distinguish between different exceptions? E.g. show a longer stacktrace for an IOException => **Conflusion**: we shouldn't filter at all as it is an unexpected Exception. Filtering out the test-runner and Atrium make sense though (which is already the case).

## TODO

- adjust ch.tutteli.atrium.domain.robstoll.lib.creating.throwable.thrown.creators.ThrowableThrownFailureHandler: 
  - overload propertiesOfThrowable add version without maxStackTrace and pass Int.MAX_VALUE to the other overload
  - deprecate the overload which still uses maxStackTrace (add `@Deprecated("...", ReplaceWith("..."))` => search for other `@Deprecated` for an example
   - same same but different for `createChildHint` -> overload without maxStackTrace and deprecate the other
  - same same but different for `ceateAdditionalHints`
   - remove the private val maxStackTrace from the constructor of ThrowableThrownFailureHandler (adjust usages accordingly) and don't pass something for maxStackTrace to propertiesOfThrowable (which means it will use the default value)
- check usages of propertiesOfThrowable, everything which is not deprecated should no longer use the deprecated overload
  - same same but different for `createChildHint`
  - same same but different for `createAdditionalHints`

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
I agree that this should be configurable. The main use case I see is that I had multiple occasions where the exception would have been helpful if I had seen more of the stack trace. However, atrium only showed me the parts that were in foreign code.

How do you plan to make this changeable? I am not sure that it is worth the effort to add a parameter to all assertions that could possibly display an exception. We could, for example, offer a property that can be configured through a file. Users could then increase this property when needed.

We could also try to get smarter about how we count stack trace lines, to get something like "show everything before we first reach user code, and a maximum of 7 lines after that.”

However, I cannot estimate how difficult and reliable it will be to determine what is user code. We could at least exclude well-known libraries (first and foremost the JDK and atrium itselft) from the stack trace count.

**Comment by robstoll** [comment]
Could you show a reporting of such an error please, that would be helpful for the discussion.

We already filter the stacktrace of a resulting AtriumError (if an exception fails) -- following an example how an error report could look like for the example above with toThrow:
```
ch.tutteli.atrium.reporting.AtriumError: expect the thrown exception: java.lang.IllegalArgumentException
◆ is instance of type: IOException (java.io.IOException)
  » Properties of the unexpected IllegalArgumentException
    » message: "arg not valid"        <1905596698>
    » stacktrace: 
      ⚬ com.example.TestKt.someMethod(test.kt:4)
      ⚬ readme.examples.A$1$1$1$1.invoke(ReadmeSpec.kt:601)
      ⚬ readme.examples.A$1$1$1$1.invoke(ReadmeSpec.kt:597)
      ⚬ readme.examples.A$1$1$1.invoke(ReadmeSpec.kt:610)
      ⚬ readme.examples.A$1$1$1.invoke(ReadmeSpec.kt:597)
  at readme.examples.A$1$1$1.invoke(ReadmeSpec.kt:607)
  at readme.examples.A$1$1$1.invoke(ReadmeSpec.kt:597)
```

However, we do not filter the stack of the unexpected Throwable (IllegalArgumentException above). Because the  first few stacks are always user code (or libraries the user used) and surely not Atrium, but could include the test-runner. IMO for toThrow the current behaviour is OK, just the limit could be different.So I am curious about your use case.


I intend that one can configure the max-stacktrace on an `Expect` basis. So either in the own assertion verb or really for one single exception:
```
expect(path, options=ExpectOptions(maxStackTrace = 30))
  .exists()
  .resolve("my-file.txt").isWriteable()
```

**Comment by jGleitz** [comment]
> I intend that one can configure the max-stacktrace on an `Expect` basis.

Ah, that is a lot better than what I had in mind :+1:.

> We already filter the stacktrace of a resulting AtriumError 

I was not really thinking about _filtering_ (i.e. not showing) the lines but rather not counting them towards the max stacktrace count.

> Could you show a reporting of such an error please, that would be helpful for the discussion.

I was thinking about something like this one:

```
expect the thrown exception: java.lang.InstantiationError
◆ is instance of type: AssertionError (java.lang.AssertionError)
  » Properties of the unexpected InstantiationError
    » message: "sun.nio.fs.UnixFileSystem"        <1153910058>
    » stacktrace: 
      ⚬ sun.reflect.GeneratedSerializationConstructorAccessor3.newInstance(Unknown Source)
      ⚬ java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      ⚬ org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
      ⚬ io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
      ⚬ io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
      ⚬ io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
      ⚬ io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
      ⚬ ...
```

When I got this one, it would have been crucial for me to find the line in _my_ code that was causing the exception. But I have realised that some sort of “automated not-counting” would likely not have helped here. On the other hand, being able to quickly increase the stack trace length on the `expect` would have helped. So I think you are right that this is the way to go.

**Comment by jGleitz** [comment]
We would make this feature easy to discover, if, when shortening stack traces, we do not simply print 

```
      ⚬ ...
```

but something like

```
      ⚬ ... (you can increase the length of printed stack traces on the expect call)
```

wording improvement needed.

**Comment by robstoll** [comment]
Hm... Maybe we shouldn't limit the stacktrace at all. We only show it in case of an unexpected Throwable. Or maybe stop once we hit test runners.

**Comment by jGleitz** [comment]
Hm. Since we are talking about _unexpected_ exceptions, it maybe really makes sense to print the whole stack trace. Even though that can get very long.

**Comment by robstoll** [comment]
Maybe my conclusion was too fast. Are all the exceptions you print in conjunction with Path assertions also unexpected?

**Comment by jGleitz** [comment]
> Are all the exceptions you print in conjunction with Path assertions also unexpected? Never due to additional explanations?

I am not sure that I understand, what you mean. Generating additional explanations should almost never yield a new exception. This should only happen in race conditions.

Additionally, the most typical IoExceptions that can occur while testing the assertion are not even shown to the user. They are replaced by an explanation.

**Comment by robstoll** [comment]
Writing from my phone and did not take a look at the code, that's why my question seem strange 😄 good it's what I expected. Could you reproduce your use case and increase the current limit to 1000 so that you see everything. I wonder if it really makes sense to print all. Maybe filtering would make sense here as well.

**Comment by robstoll** [comment]
They are already filtered :tada:
