### ISSUE TITLE
setup code coverage for windows

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#235]
## Dev-Ops related feature

We have some Windows specific code due to Path assertions => It would be nice to see them covered in the code coverage report as well. Thus:

- adjust .github/workflows/java-windows.yml 
  => see https://github.com/codecov/codecov-action for the setup of codecov (the secrret CODECOV_TOKEN is already setup)
  - please use `flags: current-windows` 
  - coverage files are created per subproject and if codecov works the same way as it does for travis-ci, then it should detect them automatically (no need to specify `file: ...`)

**Comment by sanatik** [comment]
Read about GitHub actions recently, sounds interesting for me.
I'll work on this.

**Comment by robstoll** [comment]
@sanatik do you need any help?

**Comment by robstoll** [comment]
@sanatik are you still working on this one? I am un-assigning you so that others can take over. let me know if you want to give it a go again and I re-assign you.

**Comment by name213** [comment]
Hello, If its up for grabs I would like to analyse and do this

**Comment by robstoll** [comment]
It is, go ahead 🙂👍

**Comment by robstoll** [comment]
@ivanmiklec let me know in case you need help
