### ISSUE TITLE
create bundles for the new infix API

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#236]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none and all

## Code related feature
The new infix API (infix-en_GB) needs bundles as well so that one can depend on a single dependency. We want three bundles (not mentioning the platform variations, they should be set up automatically):
- atrium-infix-en_GB
- atrium-infix-en_GB-jdk8 (includes JDK 8 specific assertion functions additionally)
- atrium-infix-en_GB-kotlin_1_3 (includes Kotlin 1.3 specific assertion functions additionally)

Following the things you need to do:
- copy the existing bundles for atrium-fluent-en_GB and adjust fluent to infix (most parts can probably be done via search & replace)
- add those new folders as modules to the project => adjust settings.gradle in the root
- adjust the SmokeTest and SmokeSpecs in the bundles, use the fluent API (e.g. rewrite ` assertThat(1).toBe(1)`  to ` assertThat(1) toBe 1`) 

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by yiss** [comment]
Hey I'm interested to work on this issue. Can you please provide more details that would be very helpful thank you

**Comment by robstoll** [comment]
@yiss what do you not understand from the description?

**Comment by yiss** [comment]
@robstoll Thanks for your prompt response. I just want to make sure that what is in my mind is what is actually requested.
So basiclly the issue is to 
 - Rename all the modules from : ```atrium-fluent-en_GB-*``` to ```atrium-infix-en_GB-*```
 - Change the test api from the old fluent api to the new infix api.
 - Change the name of ```fluent-en_GB``` to ```infix-en_GB```in the ```settings.gradle``` (not setting.xml as mentioned in the issue)

Right ?

**Comment by robstoll** [comment]
Not quite, the request is to duplicate bundles/atrium-fluent-en_GB-* and rename the duplicate to atrium-infix-en_GB-*

**Comment by yiss** [comment]
@robstoll Thank you. I'll start working on it

**Comment by yiss** [comment]
@robstoll I have a question. To use the infix api which import should I use :
  - ```assertThat(1).toBe(1)``` to ```assertThat(1) toBe 1``` does't work and I don't know which import to use. Can you help please, Thank you

**Comment by robstoll** [comment]
Ah... this does not work yet (requires #223). Please comment it out and add a `TODO #233 uncomment once toBe is implemented`

**Comment by yiss** [comment]
@robstoll Hey I just pushed my modification to my branch https://github.com/yiss/atrium can you please check and tell me if it's correct. Also I have a problem when running the tests with gradle I get some errors, but when I run it with Intellij there are no errors

**Comment by robstoll** [comment]
Could you please create a pull request, makes it easier for me to review

**Comment by yiss** [comment]
@robstoll I made a pull request #243

**Comment by robstoll** [comment]
@yiss unassigned you so that others can take over
