### ISSUE TITLE
extend IterableContainsInAnyOrderAtLeast1ElementsOfAssertionsSpec with check for empty iterables

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#239]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Test related feature
```
expect(listOf(1,2)).contains.inAnyOrder.atLeast(1).elementsOf(listOf()) //throws IllegalArgument
```
The current specs do not cover the case of passing an empty `Iterable` to elementsOf. We want to make sure that this behaviour is implemented by elementsOf

Thus:
- add this test case to IterableContainsInAnyOrderAtLeast1ElementsOfAssertionsSpec 
  => add 
  ```  
  describe("elementsOf") {  
    it("passing an empty iterable throws an IllegalArgumentException") {
      ...
    }
  }
  ```
  after the `include`

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Megamiun** [comment]
I'll work on this
