### ISSUE TITLE
Build samples as composite build

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#245]
## Dev-op related feature
We have currently two js projects in /samples. It would be nice if we could create the projects as independent projects, like we did for samples/jvm/spek and samples/jvm/junit5. Meaning with an own settings.gradle, build.gradle and gradlew so that one can really just copy the project and immediately start.

Those projects have to use a published version of Atrium and cannot use the current development version.
However, it would be nice to know if the current development version still works for those sample projects. 

Following the things you need to do:

* [ ] setup a module in misc/tools/atrium-samples-test (add folder + include it in settings.gradle in root)
  * [ ] see https://docs.gradle.org/current/userguide/composite_builds.html for how to setup a composite build and test it with the existing independent projects: samples/jvm/spek, samples/jvm/junit5 or samples/multiplatform
* [ ] turn samples/js/jasmine into an independent project
  - [ ] remove it from settings.gradle in root 
  - [ ] add own settings.gradle, gradle.build, gradlew etc. in this project
  - [ ] include it in the composite build
* [ ] turn samples/js/mocha into an independent project
  - [ ] remove it from settings.gradle in root 
  - [ ] add own settings.gradle, gradle.build, gradlew etc. in this project
  - [ ] include it in the composite build
* [ ] search for `TODO #245` and resolve them

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by iamshubh** [comment]
Hey, assign it to me

**Comment by robstoll** [comment]
@iamshubh do you need help?

**Comment by iamshubh** [comment]
> @iamshubh do you need help?

Did not get time to loom into it, will check this out!

**Comment by robstoll** [comment]
@iamshubh are you still working on it?

**Comment by assaflei** [comment]
I'll would like to take this
