### ISSUE TITLE
shortcut for LocalDate(Time) and ZonedDateTime.dayOfWeek

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#254]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature
```
import java.time.DayOfWeek.*
expect(LocalDate.now).dayOfWeek.toBe(MONDAY)
expect(LocalDate.now).dayOfWeek {
  isAnyOf(MONDAY, TUESDAY)
  ...
}

expect(LocalDateTime.now).dayOfWeek.toBe(MONDAY)
expect(LocalDateTime.now).dayOfWeek {
  isAnyOf(MONDAY, TUESDAY)
  ...
}

expect(ZonedDateTime.now).dayOfWeek.toBe(MONDAY)
expect(ZonedDateTime.now).dayOfWeek {
  isAnyOf(MONDAY, TUESDAY)
  ...
}

//instead of

expect(LocaleDate.now).feature { f(it::dayOfWeek) }.toBe(MONDAY)
expect(LocaleDate.now).feature({ f(it::dayOfWeek) }) {
  isAnyOf(MONDAY, TUESDAY)
  ...
}

...

```

Following the things you need to do (same same but different for LocaleDateTime and ZonedDateTime):

*domain*
- extend LocalDateAssertions with a function `dayOfWeek` (see LocalDateAssertions.year or month as a guideline)
- modify LocalDateAssertionsBuilder, delegate to LocalDateAssertions (see other functions as a guideline)
- delegate implementation to robstoll-lib in LocalDateAssertionsImpl (see other functions as a guideline)

*lib*
- implement _dayOfWeek in localDateAssertions by using the `ExpectImpl.feature.manual` (see month or year as a guideline)
  - add `DAY_OF_WEEK("day of week")` to DescriptionDateTimeLikeAssertion for en_GB
  - add `DAY_OF_WEEK("Wochentag")` to DescriptionDateTimeLikeAssertion for de_CH

*api* (fluent-en_GB/extensions/jdk8)
- provide a val which returns `Expect<DayOfWeek>` (see other functions as a guideline)
- provide a fun which expects an `assertionCreator`-lambda and returns `Expect<LocalDate>` (see other functions as a guideline)
- extend LocalDateFeatureAssertionsSpec in specs-common (see other funtions as a guideline) and extend it in atrium-api-fluent-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by sanatik** [comment]
I'll work on this
