### ISSUE TITLE
symlink loop detection reporting wrong

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#258]
*Affected Version*: 0.9.0-alpha
*API* (fluent-en_GB, cc or cc-infix): fluent
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## How to reproduce the problem  
on a linux system:
```
sudo mv /tmp /tmp2
sudo ln -s /tmp2 /tmp
```
Run PathAssertionsSpec afterwards -> there will be failures similar to:
```
❗❗ found a symbolic link loop: /tmp2 -> /tmp/.... -> /tmp2
```

*Edit* most of them have more to do with test-setup and not with the detection as such. This was fixed in the tests. However, one remains and here it seems the reporting is wrong. I have put a TODO in the code where I assume could be the error (did not have time to investigate further)

## Describe the bug
A symlink loop is detected even though there isn't any.

## Pre-measurements
~~The tests involving a symlink are currently skipped if a symlink is detected in the chain of Java's temporary directory.~~ => I reduced the problem to the test case `prints an explanation for link loops`

## Regression-test
We could build on macOS in addition where this problem was detected. Maybe we would find some odd behaviour of macOS's filesystem.

**Comment by jGleitz** [comment]
I have found the bug that causes the link loop to be reported wrong. Unfortunately, the code is wrong at a deeper level, as it will also produce false positives for more complicated link setups that do not actually form a loop.

I will redo and fix the logic, but might need some days time for that.

**Comment by robstoll** [comment]
No problem as macOs users should not get red tests any more.
