### ISSUE TITLE
rename containsStrictly to containsExactly

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#27]
@msmoljan is working on this one
---
*Affected Version*:  <= 0.7.0

## How to reproduce the problem  
Consider the following code snippet
```kotlin
assert(listOf(1, 2)).containsStrictly(1, 2, 3)
```

The name containsStrictly does not really tell something. One might have a very vague guess but I think almost everyone will read the docs to know what containsStrictly does. That's suboptimal in the sense that a method which tells what it does is better. Due to a false assumption within my recollection I named it this way because I figured `containsExactly` in AssertJ is actually `contains.inAnyOrder.only`. Due to this I decided that it is better if we do not use `containsExactly` to lower confusion.

However, as indicated it was a false assumption. `containsExactly` is also `contains.inOrder.only` as one would expect it. Thus we can rename it without problems to `containsExactly`

Notice:
- renaming has to be done in api-cc-en_GB, api-infix-cc-en_GB and api-cc-de_CH (rename enthaeltStrikt to enthaeltExakt)
- we need to re-add `containsStrictly` to the JVM platform after renaming it; deprecate it with a ReplaceWith to containsExactly

**Comment by msmoljan** [comment]
Hi, I'd like to take this one over.

**Comment by robstoll** [comment]
Cool that you want to resolve this issue. Let me know if you need more information.

**Comment by msmoljan** [comment]
Will do! :+1:

**Comment by robstoll** [comment]
@msmoljan Do you need any help with this one? I plan to release 0.8.0 in January

**Comment by msmoljan** [comment]
Hi @robstoll, 

I added the updated methods but didn't get around to update the tests. I'm on a trip until Monday and should be able to wrap it up in the first week of January (if that's not too late). 

Meanwhile, I created a WIP PR so you can already review the existing changes. It would be of great help if you could throw a quick look and tell me if this is implemented according to your expectations, and especially if the right files have been modified. You can find it here:
https://github.com/robstoll/atrium/pull/57/files

Thanks!

**Comment by robstoll** [comment]
That's perfect. I have left you a few comments
