### ISSUE TITLE
The example for installing a Infix API from Readme is wrong

### ISSUE THREAD

**Issue by StragaSevera** [robstoll/atrium#276]
*Affected Version*:0.9.0-alpha
*API* (fluent-en_GB, cc or cc-infix): infix
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

## How to reproduce the problem  
Follow the example of installing an Infix API from Readme:

```buildscript {
    ext { atrium_version='0.9.0-alpha' }
}
repositories {
    jcenter()
    // either use jcenter or the repository on the next line
    // maven { url "https://dl.bintray.com/robstoll/tutteli-jars" }
}
dependencies {
    testImplementation "ch.tutteli.atrium:atrium-infix-en_GB:$atrium_version"
}```

## Describe the bug
Error: `Could not find ch.tutteli.atrium:atrium-infix-en_GB:0.9.0-alpha`. This file is absent from jcenter.

## Expected behaviour
Expected to see no error and get to use the infix api ;-)

**Comment by robstoll** [comment]
Oh bummer, the new infix API does not yet exist in 0.9.0-alpha. But good to see that there is interest. You can use `atrium-cc-infix-en_GB-robstoll:0.8.0` in the meantime. For more detail: https://github.com/robstoll/atrium/blob/v0.8.0/README.md#jvm

In case you want to help bringing the new infix API forward:
https://github.com/robstoll/atrium/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22good+first+issue%22++new+infix

**Comment by robstoll** [comment]
closing this as v0.12.0 with the new infix API is going to be released soon
