### ISSUE TITLE
Move hasNext() check out of Iterable.all

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#305]
*Platform* (jvm, js, android):all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
Similar to #299 but for Iterable.none and iterable.all. Following an example:
```
expect: [1, 2, 3, 4]        (java.util.Arrays.ArrayList <1234789>)
◆ does not contain: 
  ⚬ an entry which: 
      » is greater than: 2        (kotlin.Int <1234789>)
    ✘ ▶ number of occurrences: 2
        ◾ is: 0        (kotlin.Int <1234789>)
    ✔ ▶ has at least one element: true
        ◾ is: true
```
Moreover, it should re-use the hasNext check instead of an own descriptive assertion

**Comment by tfesenko** [comment]
I'll work on this!

**Comment by robstoll** [comment]
@tfesenko note that this one is not a good first issue, I would recommend you first implement
https://github.com/robstoll/atrium/issues/31 to get a bit more into Atrium and come back to this one afterwards

**Comment by robstoll** [comment]
@tfesenko do you still plan to work on this one? Do you need any help?

**Comment by tfesenko** [comment]
@robstoll , unfortunately, I won't have the time to work on it right now.

**Comment by robstoll** [comment]
@wordhou also think that this is a good next issue and I totally agree, we should still see what went wrong in case the iterable is empty.
