### ISSUE TITLE
reword `number of occurrences`

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#306]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
Change the wording in reporting for Iterable contains.inAnyOrder from `number of occurrences` to `number of such entries` and for CharSequence.contains to `number of matches`

TODO
- [ ] change NUMBER_OF_OCCURRENCES in DescriptionIterableAssertion of en_GB accordingly
- [ ] change NUMBER_OF_OCCURRENCES in DescriptionCharSequenceAssertion of en_GB accordingly

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Jak-Sidious** [comment]
I'll work on this

**Comment by robstoll** [comment]
implemented with 7df4d4c
