### ISSUE TITLE
change assertion verb in reporting to `expected that subject`

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#307]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
Based on discussion in https://github.com/robstoll/atrium-roadmap/issues/55#issuecomment-573459025

We realised that the value of the subject can be confused with the expected value due to `expect:` and the fact that other assertion libraries use `expected` and report the expected value first. 
Therefore we came to the conclusion to change reporting to `expected that subject: ...` instead of `expect: ...`

Following the things you need to do:

*verbs*
- [ ] change ch.tutteli.atrium.api.verbs.AssertionVerb use `asserted that subject` for ASSERT and ASSERT_THAT and `expected that subject` for EXPECT

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
Can we use “expected”? To me, it sounds more correct, because the expectation is a thing of the past (we already know the result).

**Comment by robstoll** [comment]
well, then we would have to change all assertions to past tense as well to be correct right and that feels clumsy to me.

**Comment by Jak-Sidious** [comment]
I'll work on this

**Comment by robstoll** [comment]
implemented with 1b7465e
