### ISSUE TITLE
don't show number of occurrences for contains.inAnyOrder.atLeast(1)

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#310]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
Based on discussion in https://github.com/robstoll/atrium-roadmap/issues/56
We would like to see
```
◆ contains, in any order: 
  ⚬ an element which:
      »  is less than: 0        (kotlin.Int <1234789>)
        » but no such element was found.
```
<hr/>

Instead of:
```
◆ contains, in any order: 
  ⚬ an entry which: 
      » is less than: 0        (kotlin.Int <1234789>)
    ⚬ ▶ number of occurrences: 0
        ◾ is at least: 1
```

This change shall not affect cases like `atLeast(2)` or `exactly(1)`

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by susmithasrimani** [comment]
I'll work on this

**Comment by robstoll** [comment]
@susmithasrimani this isn't an easy one to start with, I suggest you do a good first issue first.
