### ISSUE TITLE
Cannot be used with Gradle 6 & JRE 8

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#338]
I am mainly opening this to show that the maintainers of this project are aware of the problem.

The underlying problem is https://github.com/robstoll/kbox/issues/26, which I am working on.

## How to reproduce the problem  
Use atrium 0.9 on a JRE version 8 with gradle 6.

## Describe the bug
The build will fail with an error message like this:

```
> Task :compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not resolve ch.tutteli.kbox:kbox:0.14.1.
     Required by:
         project : > ch.tutteli.atrium:atrium-cc-en_GB-robstoll:0.9.0 > ch.tutteli.atrium:atrium-core-api:0.9.0
      > Unable to find a matching variant of ch.tutteli.kbox:kbox:0.14.1:
          - Variant 'apiElements' capability ch.tutteli.kbox:kbox:0.14.1:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '9'.

              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
```

See, for example, https://github.com/jGleitz/string-notation/pull/14/checks?check_run_id=422070218

## Expected behaviour
The build succeeds.

**Comment by jGleitz** [comment]
@robstoll will you release atrium 0.9.1 to fix this?

**Comment by jGleitz** [comment]
(by the way: this is a good example of why “master should always be deployable”, a.k.a. the branching strategy I proposed in https://github.com/robstoll/atrium-roadmap/issues/61)

**Comment by robstoll** [comment]
japp, I thought that we merge #331 first as it should work now no? but apparently it still fails so maybe the fixes you did are not good enough?

**Comment by robstoll** [comment]
Ah no, my fault, I have not release niok correctly. I'll release 1.3.4 in a minute

**Comment by jGleitz** [comment]
Yeah, we can merge #331 first.
