### ISSUE TITLE
Avoid Duplicated Messages

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#339]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

```kotlin
object DoubleMessage : Spek({
    test("test") {
        expect("foo bar").toBe("baz")
    }
})
```

Running the above test in IntelliJ will lead to this output:

```
expected that subject: "foo bar"        <1541775512>
◆ equals: "baz"        <452140666>
ch.tutteli.atrium.reporting.AtriumError: expected that subject: "foo bar"        <1541775512>
◆ equals: "baz"        <452140666>
	at DoubleMessage$1$1.invoke(DoubleMessage.kt:5)
	at DoubleMessage$1$1.invoke(DoubleMessage.kt:7)
```

This often irritates me when scanning larger error reports because it is easy to miss the point where the errors are repeated

**Describe the solution you'd like**
When using atrium with common tools, the message is only printed once.

I don’t know who is responsible for printing the first message. I assume it’s some part of the tooling. It happens with JUnit as well as with Spek.

This can be fixed by an implementation like this:

```kotlin
actual class AtriumError internal actual constructor(message: String) : AssertionError() {
    private val printedMessage = message

    actual companion object {
        /**
         * * Creates an [AtriumError] and adjusts it with the given [atriumErrorAdjuster] before it is returned
         * (adjusting might filter the [stackTrace]).
         */
        actual fun create(message: String, atriumErrorAdjuster: AtriumErrorAdjuster): AtriumError =
            createAtriumError(message, atriumErrorAdjuster)
    }

    override fun toString(): String {
        return printedMessage
    }
}
```

which leads to output like this:

```
expected that subject: "foo bar"        <428663760>
◆ equals: "baz"        <544419202>
	at DoubleMessage$1$1.invoke(DoubleMessage.kt:5)
	at DoubleMessage$1$1.invoke(DoubleMessage.kt:7)
```

However, that is kind of ugly (we don’t pass on the message attribute, but just override `toString`). I have not found a better solution.

Note: We must make sure that the message is still shown in places where only the exception is captured (e.g. the Gradle HTML test report). For example, overriding `getMessage()` to return the empty string works in IntelliJ, but then we have no message in the gradle report.

**Comment by robstoll** [comment]
Something which bothers me as well. I guess its the test-runner which is responsible for it. Have you tried out to use another assertion library? e.g. the built-in assertEquals of junit. Is the behaviour the same?

**Comment by robstoll** [comment]
Pretty sure it is the test runner, just came across AssertJ + Spek and it shows the same behaviour

**Comment by robstoll** [comment]
`assertEquals` from kotlin.test does not have this problem. Either the junit.ComparisonException (or a similar name) is treated specially or it has implemented a successful hack.

**Comment by jGleitz** [comment]
In that case, I think we should investigate how they are doing it. Maybe it is also related to Opentest4j? (https://github.com/robstoll/atrium-roadmap/issues/39) I have not yet made any progress there.

**Comment by robstoll** [comment]
I don't know if something has changed since I last checked back in February but I see now the same duplicated error message also for kotlin.test:
```

bla ==> expected: <1> but was: <2>
Expected :1
Actual   :2
<Click to see difference>

org.opentest4j.AssertionFailedError: bla ==> expected: <1> but was: <2>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
       ...
```
The only difference is that the error message and the stacktrace it is a bit further below.

**Comment by jGleitz** [comment]
:disappointed:. Maybe we should add the hack then and see how it fares in practice?

**Comment by robstoll** [comment]
I'll make some tests first. Alternatively we could add some newlines at the end of the message to give some space between message and message + stacktrace
