### ISSUE TITLE
Include infix API in the gradle build

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#340]
https://github.com/robstoll/atrium/blob/master/settings.gradle#L65-L66:

```groovy
        //TODO re-activate with 1.0.0
//        apiWithExtensions(delegate, 'infix-en_GB')
```

I propose that we include the infix api in the gradle build, but deactivate its publications. This way, it will be included in CI and all of that.

**Comment by robstoll** [comment]
Will be done with the preparation of the next dev-cycle

**Comment by jGleitz** [comment]
Is there anything keeping us from doing it right now? I would like to add missing Infix API functions. But I think the PRs should be compiled & tested.

**Comment by robstoll** [comment]
Apparently I forgot to push. I will have time this evening.

**Comment by robstoll** [comment]
pushed it now, thus closing this issue
