### ISSUE TITLE
Lowercase Infix Keywords

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#342]
I’d find it more intuitive if the keywords for the infix API were all in lowercase, e.g.

```kotlin
expect(listOf()) toBe empty
```

instead of

```kotlin
expect(listOf()) toBe Empty
```

What do you think?

I prefer the former mainly because `empty` is an adjective here and not a substantive.

**Comment by robstoll** [comment]
Fine for me for Empty. However, wrapper-classes such as Index, Entry etc. Should be in upper IMO

**Comment by robstoll** [comment]
Also, we have to make sure that we think about it when we deprecate cc-infix, i.e. that we point to `empty` instead of `Empty`

**Comment by robstoll** [comment]
I thought about naming also wrapper-classes all in lower case. The benefit would be:
- less likely to have a name clash with other classes; e.g. `expect(path) resolve path("subfolder") asserIt { o to exist}`
- reads more like a function call

**Comment by robstoll** [comment]
I thought more about it, my last view on the topic: pseudo-keywords as empty shall be lower case, wrapper classes aka parameter objects upper case with a more descriptive identifier than just the keyword, functions as factory methods with the keyword as identifier.
For instance: `feature of(A::foo, 1)` where `of` is a function factoring a `Feature` where `Feature` is the parameter object.
