### ISSUE TITLE
configure dependabot to update samples

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#349]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Non-Code related feature
**Is your feature request related to a problem? Please describe.**
Yes, the dependencies of the samples projects get out of date if we don't update them. 

**Describe the solution you'd like**
We already use dependabot and it supports monorepos, thus we can configure it accordingly.

**Describe alternatives you've considered**
We used non-dependent projects first (still the case for mocha and jasmine samples at the time of writing)

## TODO
- [ ] setup a corresponding config file for dependabot  (https://dependabot.com/docs/config-file/) so that it scans also all subfolders of `/samples/` next to the root of the project

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by robstoll** [comment]
blocked until we decide what to do with https://github.com/robstoll/atrium-roadmap/issues/69

**Comment by robstoll** [comment]
since renovate does not support sub-projects (yet), we should setup/configure dependabot instead (samples are outdated now, so if the configuration is done correctly, then dependabot should propose to upgrade them to Atrium v0.13.0)

**Comment by uzilan** [comment]
I'd like to try to help with this one

**Comment by uzilan** [comment]
Tried setting it up in my fork and as you said @robstoll - it created PRs for updating Atrium to v0.13.0, as can be seen here: https://github.com/uzilan/atrium/pulls
