### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by HAMMER767** [robstoll/atrium#356]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(listOf(1, 2)).myDesiredFeature(...)
```

## Non-Code related feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by robstoll** [comment]
Thanks for using the feature issue template. I hope it was fun.
