### ISSUE TITLE
No proper way to call `withRepresentation` on feature with assertionCreator

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#374]
*Affected Version*:
*API* (fluent-en_GB, cc or cc-infix): `fluent-en_GB`
*Platform* (jvm, js, android): `jvm`
*Extension* (none, kotlin 1.3, jdk8): none

## How to reproduce the problem  
Consider the following (utterly stupid) code snippet:
```kotlin
expect("test").feature({ p(it::length) }) {
	isGreaterThan(3)
	isLessThan(7)
}
```

## Describe the bug
How do I call `withRepresentation` for the feature?

## Expected behaviour
There is a good way to do this.

I think the nicest way would be if I could do:

```kotlin
expect("test").feature({ p(it::length) }).withRepresentation("greatness") {
	isGreaterThan(3)
	isLessThan(7)
}
```

i.e. we add overloads for `withRepresentation`. 

Another possibility is:

```kotlin
expect("test").feature({ p(it::length) }) {
	isGreaterThan(3)
	isLessThan(7)
}.withRepresentation("greatness")
```

i.e. we make the overload of `feature` that takes an `assertionCreator` return `FeatureExpect`. However, the resulting API is less nice imho.

**Comment by robstoll** [comment]
I have not added it to the overload expecting an assertionCreator-lambda on purpose for now. I want to figure out first how/if it goes along with an immutable Expect. One can use the following though which is more or less what you expected:
```
expect("test").feature({ f(it::length) }).withRepresentation("greatness") and {
	isGreaterThan(3)
	isLessThan(7)
}
```
(side note, you can use `f` inside of `feature` also for properties)
