### ISSUE TITLE
Path.hasSameTextualContentAs

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#375]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature
```
expect(path).hasSameTextualContentAs(otherPath)
```
per default UTF-8 should be used when reading both files. 
However, one shall be able to overwrite the default, something like:
```
expect(path).hasSameContentAs(otherPath, sourceCharset=Charsets.ISO_8859_1, targetCharset=Charsets.UTF_16)
```

*Bonus* add also `hasSameBinaryContentAs`

**Comment by jGleitz** [comment]
should we rather call this `hasSameStringContent` for better clarity?

**Comment by robstoll** [comment]
AssertJ has hasSameTextualContentAs (they actually deprecated hasSameContentAs in favour of it) but IMO it is kind of the default case that one would want to compare textual content and thus would prefer a shorter version. But I am also not against using hasSameTextualContentAs if you think this is really necessary

**Comment by jGleitz** [comment]
What should be considered the default depends on what those assertions _do_. I expected `hasSameStringContent` to fail if the content cannot be parsed as a string, even if the two contents are identical. In that case, I think we should point it out in the name of the function. 

Alternatively, we could also just implement `hasSameContentAs`, which does binary comparison, and _tries_ to parse the content as UTF8 in reporting. In that case, we would not even need two different assertions.

**Comment by robstoll** [comment]
> I expected hasSameStringContent to fail if the content cannot be parsed as a string

You lost me there, I never encountered a problem reading a binary file even if the resulting text is gibberish. I also think that doing only binary comparison would not work if the source and target file is stored in a different encoding.

**Comment by jGleitz** [comment]
> You lost me there

Not all sequences of bits are valid code points in all encodings. For example, in UTF-8, code points always start with `00` or `11`, if I remember correctly. 

>  I also think that doing only binary comparison would not work if the source and target file is stored in a different encoding.

Oh, wow, okay, you also want to support comparison between different encodings? I missed that (but now I see it clearly from your proposal)

> We could implement a heuristic…

I only suggested using a heuristic in reporting, not in the actual assertion logic. But maybe that is still too complicated.

I personally prefer precision over conciseness, but my opinion is not very strong on this. I would prefer `hasSameTextualContentAs`, but I would also accept `hasSameContentAs`.

**Comment by robstoll** [comment]
So, let's go with `hasSameTextualContentAs` then

**Comment by tkech17** [comment]
where has to be added this method?

**Comment by robstoll** [comment]
atrium/apis/fluent-en_GB/extensions/jdk8/atrium-api-fluent-en_GB-jdk8-jvm/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/jdk8/pathAssertions.kt

**Comment by tkech17** [comment]
so i have to write method with 3 arguments, where last two are optionals with value UTF-8. is that right?

**Comment by tkech17** [comment]
and one simple hasSameBinaryContentAs method

**Comment by robstoll** [comment]
You got it right, let me know in case you need pointers.

**Comment by tkech17** [comment]
should i write @Since [version] in doc? or not?

**Comment by robstoll** [comment]
Yes please, we started to add the tag since v. 0.9.0 to everything which is new and public API

**Comment by tkech17** [comment]
should i add this method for infix part, too?

**Comment by robstoll** [comment]
I have not yet thought about how the API should look like, we cannot have default arguments in the infix API. Therefore I would say no unless you have an idea at hand.

**Comment by tkech17** [comment]
maybe automatically determining encoding, but don't think that there is any library that can guess the encoding 100% correctly.
the reason i was asking was that (ch.tutteli.atrium.specs.integration.PathAssertionsSpec)
is parent of both fluent and inflix PathAssertionsSpec classes.
and if i add (ch.tutteli.atrium.specs.integration.PathAssertionsSpec) these two method(from this issue), that inflix part of it should have these methods, too.
what should i do here?

**Comment by robstoll** [comment]
Workaround it similar to this one apis/cc-infix-en_GB/atrium-api-cc-infix-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/cc/infix/en_GB/CharSequenceAssertionsSpec.kt -> getContainsDefaultTranslationOfPair

use a text something like: `"not supported in this API - hasSameTextualContentAs" to ...`

**Comment by robstoll** [comment]
alternatively you can implement the following API for infix:
```
expect(path) hasSameTextualContentAs path
expect(path) hasSameTextualContentAs withEncoding(path, sourceEncoding=..., targetEncoding=...)
```
where withEncoding creates a PathWithEncoding similar to PathWithCreator

**Comment by jGleitz** [comment]
Could we do something like

```kotlin
expect(path) hasSameTextualContentAs otherPath withEncoding (UTF_8 to UTF_16)
```

That would feel more intuitive to me and I think it should be possible with infix?

**Comment by robstoll** [comment]
how would the version look like where one omits the encodings? 
```
expect(path) hasSameTextualContentAs otherPath
```
would not work any more. IMO not providing encodings is the default case and should be simple, simpler than the above is probably not possible.
Also, I think it should fit into the existing infix API. For instance, resolve is:
```
expect(path) resolve otherPath
expect(path) resolve path(otherPath) { ... }
```
in this sense I would continue with helper functions dealing with use cases where there are more than 1 parameter.
But I am curious what idea you have for the default case

**Comment by jGleitz** [comment]
I cannot speak to consistency of the API since I don’t know the API well. I generally don’t see the point of an infix API if we don’t try to make it “as infix-ish as possible”.

To how I would realise this: I didn’t think my proposal through, I just liked it. I did not think of the problem that the `hasSameTextualContentAs` matcher doesn’t “know” that another method call will follow to specify the encoding. So I have no solution :shrug: 

Another, possible, solution, would be something like 

```kotlin
expect(path) withEncoding UTF_8 hasSameTextualContentAs (otherPath withEncoding UTF_16)
```

But I am not sure that that is better.
