### ISSUE TITLE
F

### ISSUE THREAD

**Issue by 0dogg0** [robstoll/atrium#386]
*Affected Version*:
*API* (fluent-en_GB, cc or cc-infix):
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## How to reproduce the problem  
Consider the following code snippet
```kotlin
expect("this dummy text").wasReplaced.withYourCode()
```

**Comment by robstoll** [comment]
Nice, you have used the template successfully :laughing: 
Do you actually want to report a bug? If so, please open another issue and replace the descripiton
