### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by raniejade** [robstoll/atrium#4]
Any plans to support other platforms (JS, etc ...)?

**Comment by robstoll** [comment]
I am not using Kotlin for JS projects so far and I don't have a project in the pipeline where I would consider using it. Hence it is not a use case for me and thus not on my roadmap. Would you have a use case for it?

**Comment by casz** [comment]
Atrium combined with Spek would be super awesome. I think that's mainly why rani is asking 👍 

Just want to say thanks for this awesome assertion lib 💜

**Comment by robstoll** [comment]
@casz thanks for your feedback. You mean for JS right? You can use Atrium with Spek on JVM already today.

**Comment by casz** [comment]
Yes for JS it would be great for too :)

**Comment by raniejade** [comment]
There's not much option for multiplatform assertion libraries. `kotlin-test` is there but integrating test framework just to use its assertion libraries is wasteful.

**Comment by robstoll** [comment]
I totally agree that using kotlin-test just for the assertion functions is an overkill. I will look into it but I need a project where I could try it out. Do you (or anybody) have a Kotlin-JS project at hand (so that I can fork it) where you would like to use Atrium?

**Comment by robstoll** [comment]
@raniejade I have an own use case now and I could start working on this issue in v0.8.0. However, I am using spek 1.x which does not yet support multi-platform. Therefore I will wait until 2.x is out

**Comment by raniejade** [comment]
@robstoll Initial release for `2.x` won't support multiplatform yet, what we aim for the initial release is parity and re-structuring the codebase to support it. The biggest blocker for JS support is discovery, just recently discovered that the KotlinJS compiler does some special transformation to your code so kotlin-test can work on JS.

**Comment by robstoll** [comment]
I am working on this. Atrium will be turned into a multi platform project with v0.8.0

**Comment by robstoll** [comment]
implemented, will be available with the release of 0.8.0

**Comment by robstoll** [comment]
@casz I just came across this issue by coincidence and saw your wish that Atrium should support JS. In case you haven't seen it, Atrium supports JS since 0.8.0
Happy new year :champagne:

**Comment by casz** [comment]
👏 Many thanks! 🙏
Happy new year 🍾
