### ISSUE TITLE
verify if KT-23178 (isInstace in JS) is really fixed

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#400]
*Platform* (jvm, js, android): js
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We have currently a workaround implemented for 
> equals in KClass in JS not symmetric. Not working isInstance
https://youtrack.jetbrains.com/issue/KT-23178 

The workaround made sure that casting in JS works as expected. JetBrains claims to have fixed this issue. We would like to be sure that this is really the case.
We should have implemented corresponding regression tests and there the things you need to do are:

- [ ] rewrite core/api/atrium-core-api-js/src/main/kotlin/ch/tutteli/atrium/core/polyfills/kClassExtensions.kt according to the explanation given in the TODO
- [ ] run the KClassCastTest via gradle `gr :atrium-core-api-js:test` and verify that it is still green after your change. 

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Valefant** [comment]
I would like to take this one
