### ISSUE TITLE
Limit representation to 10'000 characters

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#409]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
Currently we don't define a limit for the representation. In case of e.g. file content this can fill the output drastically and depending on the CI cause the job to crash, i e. invoking a fail fast even though we don't want. Thus define a maximum in DetailedObjectFormatter of 10'000. I think this number should be reasonably big enough without crashing builds.

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jordi-farre** [comment]
I'll work on this

**Comment by robstoll** [comment]
@jordi-farre Let me know in case you need help.

**Comment by robstoll** [comment]
@jordi-farre un-assigning you so that others can take over

**Comment by Gugatke** [comment]
Could you help me by making hint for me. where should i make changes if i take this issue?

**Comment by robstoll** [comment]
In DetailedObjectFormatter where toString will be called (explicitly or implicitly).

**Comment by robstoll** [comment]
@Gugatke In DetailedObjectFormatter where toString will be called (explicitly or implicitly).

**Comment by Valefant** [comment]
You can assign me for this one 👍
