### ISSUE TITLE
Container values method does not support comparing against an existing collection

### ISSUE THREAD

**Issue by dalewking** [robstoll/atrium#419]
## Non-Code related feature
Consider a case where you have an array of values and you want to verify that a collection contains those values. The problem is that all of the methods like contains or values follow a parameter pattern like:

    expected: E,
    vararg otherExpected: E

There is no easy way to pass the array to that function. Ideally I would want to use the spread operator to pass the array as individual values but I can't really do that.

**Describe the solution you'd like**
There should just be a single vararg parameter.

**Comment by dalewking** [comment]
Discovered the elementsOf method that lets you pass an Iterable, so works by converting the array to a list

**Comment by robstoll** [comment]
exactly, please close the issue if you happy enough with `elementsOf`. Have a look at #131 in case you would like to have a shortcut and vote for it with a :+1:

**Comment by dalewking** [comment]
In my case I need inAnyOrder, so #131 would not work for me. In general, I am finding that I would like to see more support for arrays, not just lists

**Comment by robstoll** [comment]
feel free to create a `containsElementsOf` issue (or even better a PR).

The problem with better support for array is that it would require a lot of duplication. There are 9 different Array types and everywhere we support Iterable we would need to add 9 additional duplicates. That's a lot of maintenance for little gain IMO. Are you aware of `asIterable`?
Nevertheless, I am willing to help you in case you would like to tackle this problem (for instance by a generative approach).

**Comment by robstoll** [comment]
@dalewking I am going to close this issue but opened a corresponding issue at atrium-roadmap https://github.com/robstoll/atrium-roadmap/issues/75, please leave your thoughts/input there.
