### ISSUE TITLE
add elementsOf to contains.ignoreCase

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#422]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
// fluent
expect("hello").contains.ignoringCase.elementsOf(listOf("el", 'o'))

// infix
expect("hello") contains o ignoring case elementsOf listOf("el", 'o')
```

Following the things you need to do:

*fluent-api*
- [ ] add elementsOf to charSequenceContainsCreators for `CharSequenceContains.Builder<T, IgnoringCaseSearchBehaviour>` (copy the existing elementsOf and adjust)
- [ ] search for `TODO #422`  in specs and fix
- [ ] add test-case to CharSequenceContainsAtLeastAssertionsSpec covering the case that an empty iterable is passed

*infix-api*
- [ ] add elementsOf to charSequenceContainsCreators for `CharSequenceContains.Builder<T, IgnoringCaseSearchBehaviour>` (copy the existing elementsOf and adjust)
- [ ] search for `TODO #422`  in specs and fix
- [ ] add test-case to CharSequenceContainsAtLeastAssertionsSpec covering the case that an empty iterable is passed

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Miftahunajat** [comment]
Hi mr @robstoll  I would like to work on this

**Comment by Miftahunajat** [comment]
Thank you.
Should I make two different pull request for _fluent-api_ & _inflix-api_ ?

**Comment by robstoll** [comment]
as you wish, both are fine with me
