### ISSUE TITLE
shortcut Iterable.containsElementsOf

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#425]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(listOf(1, 2)).containsElementsOf(anotherList)

//instead of

expect(listOf(1, 2)).contains.inAnyOrder.atLeast(1).elementsOf(anotherList)
```

Please react with :+1:  in case you would like to see this shortcut implemented. The more upvotes the more likely I will implement it myself. You are of course welcome to implement it yourself and create a PR. Write `I'll work on it` as comment so that we can assign the task to you.

**Comment by tkech17** [comment]
i'll work on it

**Comment by robstoll** [comment]
Since it is your first contributions, I recommend that you have a look at [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution).

And a few pointers what needs to be done:
*fluent api*
- [ ] add the shortcut to fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/iterableAssertions.kt
   - [ ] add `@since 0.11.0` to KDoc
- [ ] add a ShortcutSpec to IterableContainsInOrderOnlyElementsOfAssertionSpec
  - [ ] also add a test for passing an empty iterable

*infix api* same same but different

**Comment by robstoll** [comment]
And please rebase on master in case you already forked, I made a cleanup specific for this task.

**Comment by tkech17** [comment]
I have question about adding ShortcutSpec. 
why do i need to add ShortcutSpec to IterableContainsInOrderOnlyElementsOfAssertionSpec,
as the method test inAnyOrder contains.
or maybe i did not understand what "add a ShortcutSpec to IterableContainsInOrderOnlyElementsOfAssertionSpec"

**Comment by robstoll** [comment]
Thanks for the question, the example in the description was wrong. This issue want to replace `expect(listOf(1, 2)).contains.inOrder.only.elementsOf(anotherList)`

**Comment by robstoll** [comment]
Ah.. no sorry, my fault, wrong issue, the example was correct. In this case you need to place the the ShortcutSpec into IterableContainsInAnyOrderAtLeast1ElementsOfAssertionsSpec
