### ISSUE TITLE
deprecate api-cc-infix add replacements for api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#430]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): all

## Code related feature
The new infix API (api-infix-...) which is based on `Expect` shall replace the current infix api (api-cc-infix-...) which is still based on `Assert`.

Too smooth the migration we want to deprecate all functions in cc-infix and add `ReplaceWith` so that users can use those to switch to the new API easily.

TODO (no need to do everything in one PR, file per file (e.g. PR for anyAssertions, then PR for arrayAssertions.kt etc.) is good as well):
- [ ] add `@Deprecated` annotation with a corresponding `ReplaceWith` -- copy the annotation from api-cc-en_GB and adopt to infix. 
- [ ] replace the usage in the tests.:
  1. For instance, if you have deprecated anyAssertions then go to AnyAssertionsSpec
  2. remove `@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` 
  3. replace the usages with the help of your ReplaceWith (this way we see if it works) -- in IntelliJ usually AL+ENTER ->  `Replace with...` 
   => note, in case you don't see the deprecation due to an error saying something like `symbol is defined in unnamed module` then add the following at the beginning of the file: 
       ```
       @file:Suppress("JAVA_MODULE_DOES_NOT_READ_UNNAMED_MODULE" /* TODO remove once https://youtrack.jetbrains.com/issue/KT-35343 is fixed */)
       ```
       merge with an existing `@file:Suppress` in case there is already one.
  4. re-add `@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` in the end

**Comment by Miftahunajat** [comment]
I would like to work on this

**Comment by Miftahunajat** [comment]
When I merge the 
`@file:Suppress("JAVA_MODULE_DOES_NOT_READ_UNNAMED_MODULE" /* TODO remove once https://youtrack.jetbrains.com/issue/KT-35343 is fixed */)`
with the
`@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)`
The deprecation didn't show up.
But when I removed this line `@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` and replace it with `@file:Suppress("JAVA_MODULE_DOES_NOT_READ_UNNAMED_MODULE" /* TODO remove once https://youtrack.jetbrains.com/issue/KT-35343 is fixed */)`

The Deprecation warning shows up
Any clue on this?
It looks like the deprecation didn't show when I merge both the @file:Suppress

**Comment by robstoll** [comment]
`@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` suppresses all deprecation warnings within a file. Which means, to try out your annotation you need to remove this temporarily.

**Comment by robstoll** [comment]
@Miftahunajat thanks for all your work, I un-assign you so that others see that they could work on it. Please assign you again in case you have time again to work on it.
