### ISSUE TITLE
build Atrium against jdk13 and jdk14

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#451]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We want to check if Atrium builds against jdk13 and jdk14
We already tried and saw that some tests fail as there is an issue with mockk.

Following the things you need to do:
- [ ] add jdk13 and jdk14 to the github action windows build as in this commit (you can copy and paste) https://github.com/robstoll/atrium/pull/449/files
- [ ] fix the issue with mockk

**Comment by robstoll** [comment]
Mock likely mockk does not support jdk13 and jdk14 yet. I opened a bug: https://github.com/mockk/mockk/issues/428

**Comment by oleksiyp** [comment]
I did a few commits today to MockK develop branch and test on JDK 13/14. Seems everything works. The current issue is with dokka. Not sure how am going to release it

**Comment by robstoll** [comment]
Thanks for the heads up, is there already an issue for dokka? I couldn't find any in a hurry, I would upvote it.

**Comment by oleksiyp** [comment]
This is quite a long-running issue. https://github.com/Kotlin/dokka/issues/294
