### ISSUE TITLE
add Iterator.hasNext/hasNotNext

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#460]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(iterator).hasNext()
expect(iterator).hasNotNext()
```

Following the things you need to do:

*lib*
- [ ] implement _hasNext/_hasNotNext in iteratorAssertions (a new file - see iterableAssertions as a guideline)

*domain*
- [ ] create IteratorAssertions with a function `hasNext` (see IterableAssertions as a guideline)
- [ ] create IteratorAssertionsBuilder, delegate to iteratorAssertions (see IterableAssertionsBuilder as a guideline)
- [ ] delegate implementation to robstoll-lib in new class IteratorAssertionsImpl (see IterableAssertionsImpl as a guideline)

*api-fluent*
- [ ] provide `hasNext` and `hasNotNext` in iteratorAssertions (again a new file - see iterableAssertions.kt as a guideline) 
- [ ] add `@since 0.12.0` (adapt to next release version) to KDOC of val and fun
- [ ] extend or write a separate Spec named IteratorFeatureAssertionsSpec in specs-common (see for instance IterableFeatureAssertionsSpec) and extend it in atrium-api-fluent-en_GB-common/src/test

*api-infix*
- [ ] provide `hasNext` and `hasNotNext` in iteratorAssertions (again a new file - see iterableAssertions.kt as a guideline) 
- [ ] add `@since 0.12.0` (adapt to next release version) to KDOC of val and fun
- [ ] extend or write a separate Spec named IteratorFeatureAssertionsSpec in specs-common (see for instance IterableFeatureAssertionsSpec) and extend it in atrium-api-infix-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by mspear** [comment]
I'll work on this
