### ISSUE TITLE
add Iterable.asList

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#462]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(iterable).asList().get(20).toBe(2)
```

Following the things you need to do:

*api-fluent*
- [ ] provide a fun `asList` which returns `Expect<List<T>>` (see asIterable as a guideline)
- [ ] provide a fun `asList` which expects an `assertionCreator`-lambda and returns `Expect<T>` (see asIterable as a guideline)
- [ ] add `@since 0.14.0` (adapt to next release version) to KDOC
- [ ] remodel ch.tutteli.atrium.api.fluent.en_GB.ListFeatureAssertionsSpec, extend `Spek` which includes ListSpec which you create as inner object (see ch.tutteli.atrium.api.fluent.en_GB.IterableAnyAssertionsSpec as a guideline)
      - [ ] add a IterableSpec where you convert the given list to a iterable and then use asList -> see ch.tutteli.atrium.api.fluent.en_GB.IterableAnyAssertionsSpec.IterableSpec)

*api-infix*
- [ ] provide a fun `asList` which returns `Expect<List<T>>` (see asIterable as a guideline)
- [ ] provide a fun `asList` which expects an `assertionCreator`-lambda and returns `Expect<T>` (see asIterable as a guideline)
- [ ] add `@since 0.14.0` (adapt to next release version) to KDOC
- [ ] remodel ch.tutteli.atrium.api.infix.en_GB.ListFeatureAssertionsSpec, extend `Spek` which includes ListSpec which you create as inner object (see ch.tutteli.atrium.api.infix.en_GB.IterableAnyAssertionsSpec as a guideline)
      - [ ] add a IterableSpec where you convert the given list to a iterable and then use asList -> see ch.tutteli.atrium.api.infix.en_GB.IterableAnyAssertionsSpec.IterableSpec)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Gugatke** [comment]
i'll work on it

**Comment by Gugatke** [comment]
which class should i change?

**Comment by robstoll** [comment]
@Gugatke I am not sure what you mean, all necessary changes are described in the issue description. Can you please state your question more precisely

**Comment by Valefant** [comment]
I'll work on this, if it's ok.

**Comment by robstoll** [comment]
Sure, go ahead 👍
