### ISSUE TITLE
fail if a TranslatableWithArgs has not exact arguments

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#466]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We currently do not check if the number of given arguments corresponds to the number of expected placeholders in the translatable. It would be nice if we throw an IllegalArgumentException if they do not match. This way it is more likely that we detect wrong translations.

**Comment by tkech17** [comment]
does it mean checking arguments in TranslatableWithArgs ?
in init block ?

**Comment by robstoll** [comment]
I would do it like that yes, would you like to work on this? (note your last build here https://github.com/robstoll/atrium/pull/458 would have failed if we had this check)

**Comment by tkech17** [comment]
why would it fail?
yes i want work on it

**Comment by tkech17** [comment]
also, i have question about constuctior of TranslatableWithArgs.
why do we need
constructor(translatable: Translatable, arg1: Any, arg2: Any)
        : this(translatable, createList(arg1, arg2)) ?
when there already is 
 constructor(translatable: Translatable, arg1: Any, arg2: Any, vararg otherArgs: Any)
        : this(translatable, createList(arg1, arg2, otherArgs))


-----------------

second, 
DATE_KNOWN("%tD is a %<tA") is used wrongly,
 TranslatableWithArgs(
                                TestTranslatable.DATE_KNOWN,
                                firstOfFeb2017
                            ), 

so change it into 
TranslatableWithArgs(
                                TestTranslatable.DATE_KNOWN,
                                firstOfFeb2017,
                                ""
                            ), 
or something other?

**Comment by robstoll** [comment]
> why do we need constructor(translatable: Translatable, arg1: Any, arg2: Any)

performance reasons, most of the time we don't have more than 2 arguments and therefore we don't need to allocate an array

> second DATE_KNOWN("%tD is a %<tA") is used wrongly

Oh right, that's from times where Atrium was JVM only, `%<` allows to point pack to the previous argument, so in this case the second argument points back to the first argument. That's actually valid in JVM but both `%t` as well as `%<t` is currently not supported in JS and I am not sure if we are going to support that. For now, change it to `DATE_KNOWN("%tD is a %tA")` and pass the date two times.

**Comment by robstoll** [comment]
> why would it fail?

I overlooked your question, sorry. `note your last build [...] would have failed` the last build is quite relative. I meant the build where you forgot to fix the translation for de_CH. This one would have failed as the Translatable did not have any placeholds but we delivered two arguments
