### ISSUE TITLE
jc

### ISSUE THREAD

**Issue by joshuacrites** [robstoll/atrium#469]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(listOf(1, 2)).myDesiredFeature(...)
```

## Non-Code related feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jGleitz** [comment]
This does not look like a serious attempt to create an issue. If it was, please open another issue and provide more details!
