### ISSUE TITLE
shortcut for Optional.isEmpty

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#47]
*Platform* (JVM and/or JS): JVM (only jdk8)

## Code related feature
```
expect(Optional.empty<Int>()).isEmpty()
//instead of
expect(Optional.of(1)).feature(Optional::isEmpty()) { toBe(true) }
```
However in reporting we want to see
```
expect: Optional[1]
* is: empty
```
and not
```
expect: Optional[1]
* => isEmpty: false
    * to be: true
```
Following the things you need to do:

*domain*
-:heavy_check_mark: everything is already setup for you (see OptionalAssertions, OptionalAssertionsBuilder and OptionalAssertionsImpl)

*lib*
- implement _isEmpty

*api*
- :heavy_check_mark: isEmpty is already added
- add OptionalAssertionsSpec to specs-common (see PathAssertionsSpec as guideline) and extend the spec in api-fluent-en_GB-common

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by robstoll** [comment]
depends on #107

**Comment by jGleitz** [comment]
Similar to #113 : if this method would be called `toBeEmpty`, I would find the semantics easier to understand.

**Comment by robstoll** [comment]
`Optional.isEmpty` already exists in JVM  world (> = jdk11) and I would like to stick to the names of the underlying subjects whenever possible.

**Comment by robstoll** [comment]
@arjank I have update the description regarding reporting
