### ISSUE TITLE
create maven sample project

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#470]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We currently provide an example-pom.xml and a settings.xml for maven.
It would be nicer if we actually have a full-working sample for maven.

Following the things you need to do:
- [x] setup a maven project in /samples/maven and include some tests -- up to you what runner you are using.
- [ ] build the sample in CI, add corresponding steps/jobs in .travis.yml and .github/workflows/java-windows.yml
- :no_entry_sign:  include the new sample project in the composite build of misc/tools/atrium-samples-test => won't be possible as it is not a gradle project. That's fine though.
- [x] link to the sample project in the README -> installation -> jvm (https://github.com/robstoll/atrium#jvm) -> maven

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by robstoll** [comment]
@binkley I saw that you are using Atrium in a maven context (https://github.com/binkley/spikes/blob/master/scratch/pom.xml). Would you mind creating a sample project so that others have an easier start when using Atrium as well?

**Comment by binkley** [comment]
@robstoll I'd love to!  <3

What model should I follow?  Any specific kinds of tests, etc.?

**Comment by robstoll** [comment]
nice :+1: the idea is to have a minimalistic setup of a maven project using Atrium and some test-runner (e.g. junit + jupiter) including a SampleTest. So that someone wanting to start out a new project and would like to use Atrium can basically copy the sample project.
You can come up with a SampleTest or copy an existing one (e.g. samples/jvm/junit5/src/test/kotlin/org/atriumlib/samples/junit5/SampleJvmTest.kt)

**Comment by binkley** [comment]
The sample looks good.  The only change I'd like to make: I've run into the Kotlin convention of providing "text" test method names, ie:

```
fun `expect an exception occurred`() { ... }
```
rather than:
```
fun expectAnExceptionOccurred() { ... }
```

**Comment by robstoll** [comment]
good idea, I forgot about that for JUnit. Good with me, you can also change it in the other samples if you like.

**Comment by binkley** [comment]
PR updated to separate Gradle and Maven builds.
