### ISSUE TITLE
update js samples to use the new org.jetbrains.kotlin.js gradle plugin

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#473]
*Platform* (jvm, js, android): js
*Extension* (none, kotlin 1.3, jdk8): none

## Non-Code related feature
The current samples for mocha and jasmine had been based on kotlin-examples which used the old kotlin plugin. By now, there is a new kotlin plugin (kotlin-examples is not updated though) but we could try to use the new Plugin instead. 

The new plugin claims to have a few advantages
> The plugin also provides useful testing features, for example:
> -    Source maps generation
> -    Test reports generation
> -    Test run results in the console

So that sounds good. I guess it should be easy for mocha as the default runner they use is mocha but it might actually be hard for jasmine. Therefore I suggest to start with mocha only (first PR) and try afterwards if there is a way to reconfigure the plugin to use jasmine instead (second PR).

Following the description by JetBrains:
https://kotlinlang.org/docs/reference/js-project-setup.html

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by developerfred** [comment]
I'll work on this

**Comment by robstoll** [comment]
@developerfred nice :slightly_smiling_face: 
I just pushed some cleanups https://github.com/robstoll/atrium/pull/474, please fork again or rebase on master once it is merged

**Comment by developerfred** [comment]
thanks @robstoll.

**Comment by robstoll** [comment]
@developerfred un-assigning so that pthers can take over. Let me know in case you still work on it.

**Comment by pablohildo** [comment]
I'll work on this.

**Comment by robstoll** [comment]
@pablohildo unassigning you so that others could take over

**Comment by chadmarchand** [comment]
I'll work on this
