### ISSUE TITLE
deprecate defaultTranslationOf(IgnoringCase)

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#477]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We want to remove this functionality in 1.0.0 and thus should deprecate it beforehand

Following the things you need to do:

*lib*
- [ ] add `TODO remove with 1.0.0` to  _containsDefaultTranslationOf and _containsDefaultTranslationOfIgnoringCase
     
*domain*
- [ ] deprecate CharSequenceContainsAssertions.defaultTranslationOf with `@Deprecated("Will be removed with 1.0.0") no need for a replacement
- [ ]  same same but different for CharSequenceContainsAssertions.defaultTranslationOfIgnoringCase 

- [ ] suppress deprecation in CharSequenceContainsAssertionsBuilder

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Gugatke** [comment]
I'll work on this

**Comment by robstoll** [comment]
@Gugatke let me know in case you need help

**Comment by robstoll** [comment]
@Gugatke un-assinging you so that others can take over

**Comment by z13z** [comment]
I'll work on this
