### ISSUE TITLE
Allow that Sequence and Array can be passed to elementsOf

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#479]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
We have several places where elementsOf is in use. Following the current places in the fluent-api (at the time of writting):
```
expect(listOf(1,2)).containsElementsOf(...)
expect(listOf(1,2)).contains.inAnyOrder.atLeast(1).elementsOf(...)
expect(listOf(1,2)).containsExactlyElementsOf(...)
expect(listOf(1,2)).contains.inOrder.only.elementsOf(expectedIterable)

expect("hello world").contains.elmentsOf(...)
expect("hello world").contains.ignoringCase.elmentsOf(...)
expect("hello world").contains.ignoringCase.atLeast(1).elementsOf(...)
expect("hello world").containsNot.elementsOf(listOf("a", 2))
expect("hello world").containsNot.ignoringCase.elementsOf(listOf("a", 2))
```

Those functions require currently that an Iterable is passed. We would like to allow that one can also pass other types where we can iterate over such as Sequence or one of the 9 Array types. However, we don't want to pollute the API with that many overloads. Instead we want one overload which accepts an `IterableLike<T>` which is not much more than a typealias for Any (similar to the existing `CharSequenceOrNumberOrChar`. 
For now we need two overloads in order to be binary backward compatible.

Following the things you need to do:

*domain-api*
- [ ] add typealias `IterableLike<T>` in package typeutils

*lib*
- [ ] rewrite `toVarArg`, accept IterableLike<T> and check that the given type is either Iterable or Sequence or one of the 9 Array types (see arrayAssertions.kt for the types).

*api-fluent*
- [ ] duplicate all elementsOf functions as well as containsElementsOf and containsExactlyElementsOf and expect an IterableLike instead where:
   - [ ] you add `@since 0.13.0` (adopt to next version) to KDoc
   - [ ] you add a notice to KDoc saying:
        ```
        * Notice that a runtime check applies which assures that only [Iterable], [Sequence] 
        * or one of the [Array] types are passed.
        ```
- [ ] add a TODO to the existing elementsOf functions `TODO remove with 1.0.0`

*api-infix*
- same same but different
## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by anesabml** [comment]
Hi, can I work on this?

**Comment by robstoll** [comment]
Sure 👍
