### ISSUE TITLE
accept date and time as string in ISO 8601 format for ChronoLocalDateTime

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#481]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature
```
expect(LocalDateTime.now()).isAfter("2020-04-28T12:00")

//instead of

expect(LocalDateTime.now()).isAfter(LocalDateTime.of(2020,4,28,12,0))
```

Following the things you need to do:

*atrium-logic*:
- [ ] duplicate each method in chronoLocalDateTimeAssertions.kt and:
  - [ ] accept a String instead of a ChronoLocalDateTime and parse it to LocalDateTime and pass it to the existing overload where the following formats shall be supported. This is a slight deviation of ISO 8601, e.g. we do not want to support the alternative notation e.g. 20200401120001 instead of 2020-04-01T12:00:01
        * yyyy-mm-ddThh:mm:ss.sss (up to 9 digits for nanoseconds)
        * yyyy-mm-ddThh:mm:ss
        * yyyy-mm-ddThh:mm
        * yyyy-mm-dd
        => hint: all but the last point is supported by LocalDateTime.parse. 
        Note that #482 deals also with parsing DateTime. You should reuse the logic from there if #482 is already implemented.

*api-fluent*
- [ ] duplicate each method in chronoLocalDateTimeAssertions.kt and:
  - [ ] accept a String instead of a ChronoLocalDateTime - call the corresponding domain function
  - [ ] change since to 0.12.0 (adapt to current [milestone](https://github.com/robstoll/atrium/milestones))
- [ ] add the string version to ChronoLocalDateTimeAssertionsSpec:
  - [ ] add an object StringSpec, create functions in the companion object which corresponds to the signature of the existing functions (i.e. accept a ChronoLocalDateTime) where inside you turn the ChronoLocalDateTime into a string in ISO format and pass it to your new function
 - [ ] add `describe("wrong string format")` after the `include(...)` and add the following test-cases (use a map and forEach to generate the test-cases -- see DelegatingAssertionCheckerSpec for an example):
   - one passes a DateTime in format yyyymmddhhmmssSSS
   - one passes a DateTime in format yyyymmddhhmmss
   - one passes a DateTime in format yyyymmddhhmm
   - one passes a DateTime in format yyyymmdd
   - one passes a DateTime in format yyyy-m-ddThh:mm
   - one passes a DateTime in format yyyy-mm-dThh:mm
   - one passes a DateTime in format yy-mm-ddThh:mm
   - one passes a DateTime in format yyyy-mm-ddTh:mm
   - one passes a DateTime in format yyyy-mm-ddThh:m
   - one passes a DateTime in format yyyy-mm-ddThh:mm:s
   - one passes a DateTime in format yyyy-mm-ddthh:mm (note lower case t)
 - [ ] add `describe("allowed shortcuts")` with the following test cases:
    - one passes a DateTime in format yyyy-mm-ddThh:mm:ss
    - one passes a DateTime in format yyyy-mm-ddThh:mm
    - one passes a DateTime in format yyyy-mm-dd
 - [ ] add the string version to the ambiguityTests in ChronoLocalDateTimeAssertionsSpec

*api-infix*
- same same but different

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by rkiselev** [comment]
I'll work on this

**Comment by robstoll** [comment]
implemented with https://github.com/robstoll/atrium/pull/556
