### ISSUE TITLE
adjust reporting for isLess/GreaterThanOrEqual

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#483]
*Platform* (jvm, js, android):
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(1).isGreaterThanOrEqual(2)
```
results in reporting
```
expected that subject: 1
* is greater or equals: 2
```

Instead we would like to see

```
expected that subject: 1
* is greater than or equal to: 2
```

Same goes for isLessThanOrEqual

Following the things you need to do:

*translation*
- [x] introduce IS_LESS_THAN_OR_EQUAL and IS_GREATER_THAN_OR_EQUAL in DescriptionComparableAssertion for en_GB and adjust accordingly
   - [x] add `@since 0.12.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC 
- [x]  introduce IS_LESS_THAN_OR_EQUAL and IS_GREATER_THAN_OR_EQUAL in DescriptionComparableAssertion for de_CH; you can use the same text for de_CH as the current though
   - [x] use `ist weniger als oder gleich wie` for IS_LESS_THAN_OR_EQUAL
   - [x]  use `ist grösser als oder gleich wie` for IS_GREATER_THAN_OR_EQUAL
   - [x] add `@since 0.12.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC 
- [x] deprecate IS_GREATER_OR_EQUALS and IS_LESS_OR_EQUALS in en_GB and de_CH with something like:
      ```
      @Deprecated("Use IS_LESS_THAN_OR_EQUAL; will be removed with 1.0.0", ReplaceWith("DescriptionComparableAssertion.IS_LESS_THAN_OR_EQUAL"))
      ```
- [x] replace usages of the deprecated enum values (you ALT+ENTER -> `Replace with ...`) to see if the ReplaceWith works as you would expect

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Russiancold** [comment]
Hi! I'd like to work on this.

**Comment by robstoll** [comment]
@Russiancold un-assigning you so that others could take over.

**Comment by z13z** [comment]
I'll work on this
