### ISSUE TITLE
introduce Comparable.isEqualComparingTo

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#484]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(comparable).isEqualComparingTo(otherComparable)

//instead of

expect(comparable.compareTo(otherComparable)).toBe(0)
```

And in reporting we want to see:
```
expected that subject: 1
- is equal comparing to: 2
```

Following the things you need to do:

*lib*
- [x] implement _isEqualComparingTo in comparableAssertions.kt (see other functions)
  - [x] add DescriptionComparableAssertion.IS_EQUAL("is equal comparing to") for en_GB
  - [x] add DescriptionComparableAssertion.IS_EQUAL("ist gleich wie") for de_CH 

*domain*
- [x] extend ComparableAssertions with a function `isEqualComparingTo` (see other functions as a guideline)
- [x] modify ComparableAssertionsBuilder, delegate to comparableAssertions (see other functions as a guideline)
- [x] delegate implementation to robstoll-lib in ComparableAssertionsImpl (see other functions as a guideline)

*api-fluent*
- [x] provide the fun `isEqualComparingTo` in comparableAssertions.kt delegating to domain  (see other functions as a guideline)
- [x] add `@since 0.12.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [x] add `isEqualComparingTo` to ComparableAssertionsSpec in specs-common and adjust ComparableAssertionsSpec in atrium-api-fluent accordingly

*api-infix*
- [x] same same but different

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jaibhavaya** [comment]
I'll work on this

**Comment by jaibhavaya** [comment]
PR is in, this is my first contribution to anything open source, so I'm not totally sure if I have to do anything to link it to this issue.

**Comment by robstoll** [comment]
No need to link it, I am going to review your PR tomorrow. I hope your first contribution was fun so far.

**Comment by jaibhavaya** [comment]
It was great.  Thanks so much for outlining this, it made it super approachable and was a blast to do.
