### ISSUE TITLE
merge jdk8 extension into jvm module

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#493]
*Platform* (jvm, js, android): jvm
*Extension* (none, kotlin 1.3, jdk8): jdk8

## Code related feature
We introduced the jdk8 extension in v0.9.0 because we thought it would cause problems for android devs since it contains classes which are not available in all Android SDK API levels (e.g. java.nio.file.Files was only introduced in API level 26). Since we could show in #167 that this should not be a proble and that the module-info.class bug (see #52 for details) does no longer occur, we can now merge the jdk8 extension into the normal jvm module.

Following the things you need to do:

*api-fluent*
- [x] copy the files from the extension into the jvm module (i.e. copy all files in apis/fluent-en_GB/extensions/jdk8/atrium-api-fluent-en_GB-jdk8-jvm/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/jdk8 to apis/fluent-en_GB/atrium-api-fluent-en_GB-jvm/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB 
- [x] copy the tests from the extension into the jvm module
- [x] adjust the packages in the normal jvm module (main and test) accordingly, i.e. remove jdk8 -- I suggest to search for `package ch.tutteli.atrium.api.fluent.en_GB.jdk8` and replace with `package ch.tutteli.atrium.api.fluent.en_GB`
- [x] deprecate all functions in the extension and point to the function in the normal jvm module. For instance, for `fun <T : ChronoLocalDate> Expect<T>.isBefore(expected: ChronoLocalDate): Expect<T>` in `chronoLocalDateAssertions.kt` you would add: 
   ```
   @Deprecated("Use the function from the normal jvm module; the jdk8 extension will be removed with 1.0.0", ReplaceWith("ch.tutteli.atrium.api.fluent.en_GB.isBefore"))
   ```
*api-infix*
- [ ] same same but different.

*others*
- [x] remove the mentionings of the jdk8 extension in the README.md 
- [x] remove the package descriptions for jdk8 from misc/kdoc/packages.md

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by assaflei** [comment]
I'll take this

**Comment by robstoll** [comment]
🙂👍
(you should be able to assign yourself)
