### ISSUE TITLE
cache gradle and dependencies in github actions

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#495]
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): all

## Non-Code related feature
We currently have no cache in place for github actions. I guess we could reduce the build time quite a bit if we integrate it.

Things TODO:
- :no_entry_sign: cache gradle and dependencies: https://github.com/actions/cache/blob/master/examples.md#java---gradle => due to a Kotlin bug (see https://youtrack.jetbrains.com/issue/KT-39109)
- [x] cache also maven dependencies (for maven sample project): https://github.com/actions/cache/blob/master/examples.md#java---maven
- [x] cache android.jar which we download for d8: https://github.com/actions/cache#skipping-steps-based-on-cache-hit - skip downloading in case of a cache-hit

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by assaflei** [comment]
I'll take this
