### ISSUE TITLE
add Path.contains as shortcut for Path.isDirectory + Path.resolve + Path.exists

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#590]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(path).contains("test.txt", "dummy.log")

//instead of

expect(path).isDirectory() and {
  resolve("test.txt") { exists() }
  resolve("dummy.log") { exists() }
}
```

Following the things you need to do:

*api-fluent*
- [ ] provide a fun `contains` which expects `path: String, vararg otherPaths: String` and returns `Expect<T>` (see resolve with expect an assertionCreator in pathAssertions.kt as a guideline)
- [ ] add `@since 0.14.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add `contains` to PathAssertionsSpec in specs-common and extend it in atrium-api-fluent-en_GB-common/src/test

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by SylvainGirod** [comment]
Hello, can I work on this ?

**Comment by robstoll** [comment]
Sure

**Comment by ezesalas7** [comment]
Hello, I'll work on this...

**Comment by SylvainGirod** [comment]
> Hello, I'll work on this...

I think you can if @robstoll is ok. I couldn't manage to take the time to work on this.

**Comment by robstoll** [comment]
@ezesalas7 go ahead and let me know if you need help.
@SylvainGirod come back once you have time again, your help is always appreciated.

**Comment by ezesalas7** [comment]
Thanks @robstoll, I am setting up the project now. First time contributing to open source, pretty exited! Hope I can get It done :)

**Comment by jgrgt** [comment]
I'll work on this

**Comment by robstoll** [comment]
@jgrgt there is already someone working on this. Please take another issue unless @ezesalas7 does not have time

**Comment by robstoll** [comment]
@jgrgt sorry, I have not seen that @ezesalas7 unassigned himself. So go ahead :+1:

**Comment by robstoll** [comment]
@jgrgt unassigning so that others can take over. Let us know in case you still work on it

**Comment by jgrgt** [comment]
@robstoll Sorry about the lack of updates, I got stuck. Naming the function `contains` caused naming conflicts I could not resolve. I have something working with `containss` as a name for now. And still the build fails at the moment, with:

```
> Task :atrium-api-infix-en_GB-jvm:compileTestKotlin FAILED
e: /home/jens/Code/GitHub/atrium/apis/infix-en_GB/atrium-api-infix-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/infix/en_GB/PathAssertionsSpec.kt: (3, 30): Unresolved reference: fluent
e: /home/jens/Code/GitHub/atrium/apis/infix-en_GB/atrium-api-infix-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/infix/en_GB/PathAssertionsSpec.kt: (26, 24): Unresolved reference: containss
```

**Comment by robstoll** [comment]
No problem, re-assigned you. Please push everything you have, always easier to review.
About the particular issue. You try to access api-fluent from api-infix. Check your imports. In api-infix you should not have `import ch.tutteli.atrium.api.fluent`

**Comment by jgrgt** [comment]
@robstoll I pushed my code to a branch on my clone. Here's a diff https://github.com/robstoll/atrium/compare/master...jgrgt:path-contains?expand=1 Not sure if I'm allowed to create a 'WIP' pull request for this or not.

**Comment by robstoll** [comment]
You can always create a WIP pull request, no problem. Please do so, easier to keep track of changes for me.

**Comment by jGleitz** [comment]
I know I am late to the party, but I have an objection against this method being called `contains`. `Path` implements `Iterable<Path>`, which means that there is `Expect<Path>.contains(p: Path)`. This leads to an odd situation:

```Kotlin
expect(Path.of("/foo/bar")).contains(Path.of("bar")) // will succeed
expect(Path.of("/foo/bar")).contains("bar") // will or will not succeed, depending on the content of the /foo/bar directory
```

I think it is bad to `Expect<Path>.contains(p: Path)` and `Expect<Path>.contains(s: String)` with completely different semantics. Intuitively, I would expect `Expect<Path>.contains(s: String) = this.contains(Path.of(s))`.

Since it is not released yet, now would be the time to rename the method. Do you agree that we should? I’d suggest something like `hasDirectoryEntry`.

**Comment by robstoll** [comment]
@jGleitz good you spotted this. I forgot that Path implements Iterable

**Comment by jGleitz** [comment]
I am glad to raise a PR. Is `hasDirectoryEntry` good?

**Comment by robstoll** [comment]
@jGleitz I think name is OK and better than `hasEntry` as this would not imply that the path is a directoy

**Comment by jGleitz** [comment]
How is this assertion supposed to behave for symbolic link entries? _I_ would expect that the assertion resolves a symbolic link if the subject is a symbolic link, but does not follow symbolic links for the directory entries. However, the current implementation also resolves symbolic links for the file system entries.

For example, this assertion: 

```kotlin
expect(Path.of("/foo/bar")).hasDirectoryEntry("baz")
```

would fail with the current implementation if `/foo/bar/baz` is a symbolic link that points to a non-existent location. However, I intuitively would expect the assertion not to fail in this case.

What do you think?

**Comment by robstoll** [comment]
nice catch, I agree, I would intuitively also expect it to hold if the link is there regardless where it points to.
So... since the implementation will be more complicated than just a combination of two functions, I suggest you move it to logic in your PR.
