### ISSUE TITLE
Add Expect.because to Document Assertions

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium#627]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```kotlin
expect(proposeAFileName()).containsNot("?").because(
   "? is not allowed in file names on Windows"
)
```

I sometimes find myself in situation where I write assertions that are not obvious. By that, I mean that it is either not clear why the assertion should be required to hold, or what the assertion is supposed to test, for example because it tests in some indirect manner. I usually leave a comment in the code, however, I don’t see this comment when I look at the test report of my CI run. It would be great if I was able to document obscure assertions in a way that makes them clear to anybody reading the test report.

You might object that obscure assertions are a bad smell and that they should be avoided, which is totally true. However, from my experience, they cannot always be avoided. Adding a helper to deal with such situations would be great.

**Describe the solution you'd like**
Add a function `Expect<T>.because(reason: String): Expect<T>` that documents the reason for the current assertion. Maybe also add an overload `Expect<T>.because(reasonCreator: () -> String): Expect<T>` for cases where creating the reason might be expensive.

The output for assertions with a reason might look like this:

```
expected that subject: really?        (sun.nio.fs.UnixPath <369206678>)
◆ ▶ file name: "really?"        <1746615583>
    ◾ does not contain: 
      ⚬ value: "?"        <93126369>
      🛈 because ? is not allowed in file names on Windows
        ⚬ ▶ number of matches: 1
            ◾ is: 0        (kotlin.Int <2122512723>)
```

**Describe alternatives you've considered**
Not implementing such a feature and sticking to comments.

**Comment by jGleitz** [comment]
The design was inspired by [Gradle’s possibility to add reasons for dependencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:documenting-dependencies).

**Comment by robstoll** [comment]
Thanks for the report. I am totally in favour of adding something like that. In fact, adding notes/remarks is on the roadmap https://github.com/robstoll/atrium-roadmap/issues/15 
We also have adding failure hints on the roadmap (https://github.com/robstoll/atrium-roadmap/issues/9). I am not sure which one is the one you would want to use.
let's discuss ideas there and come back once we are settled.
I am closing this one, please copy your example and paste it in atrium-roadmap

**Comment by jGleitz** [comment]
Oh, I see. Sorry for the duplication, I forgot to check the roadmap!

**Comment by robstoll** [comment]
no problem
