### ISSUE TITLE
add Path.isAbsolute

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#629]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(path).isAbsolute()

//instead of

expect(path).feature("isAbsolute") { isAbsolute() }
```

Following the things you need to do:

*logic*
- [ ] extend PathAssertions with a function `isAbsolute` (see other is... functions in PathAssertions as a guideline)
- [ ] implement isAbsolute in DefaultPathAssertions.kt

*api-fluent*
- [ ] add isAbsolute to pathAssertions.kt
- [ ] add `@since 0.14.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add isAbsolute to Path(Feature)AssertionsSpec in specs-common

*api-infix*
- [ ] same same but different (see existing `toBe ...` functions)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
I’d vote for also adding `Path.isRelative()`. First, I can imagine use cases for it (although I currently have none), second, and more importantly, I think this follows from the [principle of last astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): If there is `isAbsolute`, I expect there to be `isRelative`.

**Comment by robstoll** [comment]
I agree, I created another issue #630

**Comment by mtadmk** [comment]
I'll work on this

**Comment by jGleitz** [comment]
@mtadmk note that @jakubriegel is working on #630. You will be touching the same parts of the code, which means that

 a) you are very likely to have merge conflicts
 b) doing both at once might be simpler


I am not discouraging you from taking this ticket! I just wanted to point it out to spare you the frustration of having to fix conflicts. Maybe you can contact @jakubriegel and agree on how you want to proceed.

**Comment by jakubriegel** [comment]
@jGleitz good point. It will be literally the same code. I planned to take that one to - sorry for not stating this here. 
@mtadmk maybe you will wait for my pr and that create branch from my changes?

**Comment by jakubriegel** [comment]
@mtadmk my pr https://github.com/robstoll/atrium/pull/632

**Comment by robstoll** [comment]
@mtadmk still interested in doing this?

**Comment by jakubriegel** [comment]
@robstoll if @mtadmk is not up for this issue, I can take it 👌

**Comment by robstoll** [comment]
@jakubriegel please go ahead :+1:
