### ISSUE TITLE
add Path.isRelative

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#630]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(path).isRelative()

//instead of

expect(path).feature("isRelative") { isRelative() }
```

Following the things you need to do:

*logic*
- [ ] extend PathAssertions with a function `isRelative` (see other is... functions in PathAssertions as a guideline)
- [ ] implement isRelative in DefaultPathAssertions.kt

*api-fluent*
- [ ] add isRelative to pathAssertions.kt
- [ ] add `@since 0.14.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add isRelative to Path(Feature)AssertionsSpec in specs-common

*api-infix*
- [ ] same same but different (see existing `toBe ...` functions)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jakubriegel** [comment]
I'll work on this **#hactoberfest**
