### ISSUE TITLE
Atrium stops working for JS with Kotlin 1.4

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#631]
*Affected Version*: almost all, as soon as Kotlin 1.4 is used by the consuming project
*API* (fluent-en_GB, infix-en_GB): both
*Platform* (jvm, js): js
*Extension* (none, kotlin 1.3): none

## How to reproduce the problem  
See https://github.com/robstoll/atrium/pull/620

And https://youtrack.jetbrains.com/issue/KT-42610
## Describe the bug
CoroutineBasedLocale... is using coroutines from the experimental package. This one was dropped with Kotlin 1.4

## Expected behaviour
Atrium should also work with Kotlin 1.4

Rewrite CoroutineBased... Simplest is to pre-compute everything by putting the Locale into a List and turn the list into a Sequence

**Comment by chadmarchand** [comment]
I'll work on this

**Comment by chadmarchand** [comment]
@robstoll Is there a trick to running the spec tests? I'm trying to run LocaleOrderDeciderSpec, have tried a couple different methods to no avail (gradle tasks and the Spek plugin for IntelliJ). The Spek plugin gives me this error when I try to run with Run -> Speks in package ch.tutteli... (Or Run -> tests in package ch.tuttelli...)

`/media/hdd/projects/atrium/core/api/atrium-core-api-jvm/src/module/module-info.java
java: modules are not supported in -source 1.8
  (use -source 9 or higher to enable modules)`

If I understand correctly the java versions should come from the gradle file so I shouldn't have to change any IntelliJ project settings, but I've tried anyways to change to Java 9 and still have the same issue.

**Comment by robstoll** [comment]
I am using 
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

With the Spek Framework plugin 2.0.13-IJ2020.2

And I can just click on the play gutter in core/robstoll-lib/atrium-core-robstoll-lib-common/src/test/kotlin/ch/tutteli/atrium/core/robstoll/lib/reporting/translating/LocaleOrderDeciderSpec.kt and the test is executed as it should (and is green)

However, what I cannot do is clicking on a package and run all tests -> it seems like in this case spec is not used (most likely kotlin.test kicks in)

Note that you need to reload the gradle project within intellij if you change the java version. We don't include modules in case of jdk8 because they are not supported.

**Comment by chadmarchand** [comment]
Thanks, using the gutter icon seems to have done the trick.

**Comment by robstoll** [comment]
https://github.com/robstoll/atrium/pull/620 was successful with the fix :+1:
