### ISSUE TITLE
improve performance of containsNoDuplicates

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#636]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
We currently use the following algorithm to filter all elements of a list which have duplicates:
```
list.count { e -> e == element } > 1
``` 
Which means in the worst case we iterate the whole list for every element in the list. I assume there are better ways to do this. Research and improve the algorithm.

TODO:
- adjust the algorithm in DefaultIterableLikeAssertions

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
> I assume there are better ways to do this. 

Iterating over the collectiong while building a HashSet of the elements and adding any element that already is in the HashSet to the result collection has an expected runtime complexity of O(n) as opposed to the current O(n²) (assuming a O(1) implementation of `hashCode`/`equals`).

**Comment by robstoll** [comment]
@jGleitz I did on purpose not give any further hints because it's hacktoberfest and a good issue for newbies. If you don't mind, delete your comment. You can still give the hint in case the one tackling the problem needs help 😉

**Comment by jGleitz** [comment]
sorry, I didn’t get that :facepalm:. I was only trying to be helpful!

**Comment by robstoll** [comment]
Always appreciated 👍

**Comment by mohammaddvi** [comment]
Hi, I want to work on this issue and have a question and an idea.

**Comment by robstoll** [comment]
Go ahead, what's your question?

**Comment by mohammaddvi** [comment]
I`ve done actually but I want to be sure about my implementation. This method just wants to know there is duplicate or not, yes?

**Comment by robstoll** [comment]
Please push what you already have, (e.g. as draft PR) it's always easier to talk about code when one sees it.

**Comment by shytnik-igor** [comment]
I'll work on this

**Comment by shytnik-igor** [comment]
@robstoll, What else can I do about this issue?

**Comment by robstoll** [comment]
It's all good, I think the current implementation is fine. Thanks. 
But you could throw an eye on the remaining open issues
