### ISSUE TITLE
update gradle wrapper to latest version

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#637]
## Code related feature
update gradle wrapper in:
- root
- all the samples (those are independent projects)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by fejd** [comment]
I'll work on this

**Comment by praful0203** [comment]
I will work on this

**Comment by robstoll** [comment]
@praful0203 there is already fejd working on this one. There are other good first issues
