### ISSUE TITLE
add samples for arrayAssertions of api-fluent 

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#644]
## Code related feature
See for the initial request: https://github.com/robstoll/atrium/issues/624

With this issue we want to add samples for arrayAssertions.kt of api-fluent

Following the things you need to do:
 
*api-fluent*
- [ ] create ArrayAssertionSamples in apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples
  - [ ] add one function per function in arrayAssertions.kt (see AnyAssertionSamples)
  - [ ] refer to the sample in the KDoc of the corresponding function in arrayAssertions via `@sample` (check out `toBe` in anyAssertions.kt to see how you have to refer to the sample)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jdornieden** [comment]
I'll work on this
