### ISSUE TITLE
add samples for throwableExpectations of api-fluent

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#658]
## Code related feature
See for the initial request: https://github.com/robstoll/atrium/issues/624

With this issue we want to add samples for throwableExpectations.kt of api-fluent

Following the things you need to do:
 
*api-fluent*
- [ ] create ThrowableExpectationSamples in apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples
  - [ ] add one function per function in throwableExpectations.kt and non deprectated function in throwableAssertions (see AnyExpectationSamples)
  - [ ] refer to the sample in the KDoc of the corresponding function in throwableExpectations and throwableAssertions via `@sample` (check out `toEqual` in anyExpectations.kt to see how you have to refer to the sample)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Evansb2250** [comment]
Hi @robstoll I wanted to know if this issue has been resolved? If not I would like to attempt to resolve it.

**Comment by robstoll** [comment]
@Evansb2250 not yet, thanks for working on it

**Comment by Evansb2250** [comment]
@robstoll you're welcome, I've never done anything like this before, so I will try my best to be of some help.

**Comment by Evansb2250** [comment]
Hi @robstoll  I've looked at throwableExpectations.kt and throwableAssertions.kt, and I am not entirely sure how to provide a sample of using the functions in the files.
Could you provide me hint please ?

**Comment by robstoll** [comment]
@Evansb2250 You can copy an existing samples file, for instance AnyExpectationSamples there you see how you need to write a sample function. The usage of e.g. `toThrow` is explained here and gives a good starting point I guess: https://github.com/robstoll/atrium#expect-an-exception
Also, search for uses in the project, Tests etc. should give you further hints how the functions are used.
