### ISSUE TITLE
rename withFailureHint to withHelpOnFailure

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#671]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Currently one can create hints in case of an assertion failure by using `withFailureHint`. In https://github.com/robstoll/atrium-roadmap/issues/9 we came to the conclusion that `withHelpOnFailure` would better state the intend. 

Following the things you need to do:

*logic*
- [ ] find everything containing `with...FailureHint`, duplicate and rename to `withHelpOn...Failure`  
- [ ] deprecate everything you find containing `FailureHint` and point to the new functionality, i.e add a `@Deprecated("Use ...; will be removed with 1.0.0")`  and replace `...` accordingly. 

*API*
there shouldn't be any change in the APIs

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by rishujam** [comment]
I'll work on this

**Comment by rishujam** [comment]
@robstoll  I am new to Open source. I have one query do I need to open each and every file in this project and check if it contains withFailureHint method and then refactor it or is there any other way I need to proceed.

**Comment by robstoll** [comment]
Upfront, it's up to you how you do it. I think your approach is good but better search for `with.*FailureHint` using regex
![image](https://user-images.githubusercontent.com/5557885/115207681-19ccff80-a0fc-11eb-8341-b55c1a58206b.png)

**Comment by rishujam** [comment]
@robstoll I am not able to do that sorry

**Comment by robstoll** [comment]
@rishujam no worries. Let me know in case you would still like to do it but need more help.

**Comment by offgridauthor** [comment]
I'd like to work on this issue.

**Comment by DurveshKumarPal** [comment]
hey, can you assign me that issue.

**Comment by robstoll** [comment]
@offgridauthor are you still working on this one? @DurveshKumarPal would like to take over

**Comment by robstoll** [comment]
@DurveshKumarPal there are also other issues where we could use your help and are not assigned yet in case you already want to start programming:
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by offgridauthor** [comment]
> @offgridauthor are you still working on this one? @DurveshKumarPal would like to take over

Go for it. Things have shifted and I won't be able to tackle this right now.

**Comment by stevenlmcgraw** [comment]
I'll work on this.
