### ISSUE TITLE
add samples for iteratorAssertions of api-infix

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#677]
*Platform* (all, jvm, js, android): all
*Extension* (none, kotlin 1.3): none

## Code related feature
We also want to provide samples for the infix api

Following the things you need to do:
- [ ] copy IteratorAssertionsSample from fluent-api, adjust imports `...api.fluent...` to `...api.infix...` and ajdust the samples accordingly (always use the infix syntax, never the fluent).
- [ ] check that the sample in the KDoc Intellij shows looks good (ALT+Mouse-click on function name)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by lilimapradhan9** [comment]
I'll work on this
