### ISSUE TITLE
show more than first line when using mocha test runner

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#691]
*Platform* (all, jvm, js): js
*Extension* (none, kotlin 1.3): none

## Code related feature
It seems like mocha or maybe also the gradle plugin of Jetbrains is configured per default in a way that we see only the first line of an error in the terminal. We see the full message in the resulting gradle test report html though.

It would be nice, if we would see the whole message and not just the first line.
I am totally not sure how to do this, can only give the following hint, that it might be we can configure mocha somehow via the following (in samples/js/build.gradle)

```
kotlin {
    js {
        nodejs{
            testTask{
                useMocha{
                        // config here
                }
            }
        }
    }
}
```
I suggest you let /samples/js/src/test/kotlin/org/atriumlib/samples/mocha/SampleJsTest.kt fail on purpose (e.g. set `toBe(2)`) and run the sample afterwards:
```
cd samples/js
./gradlew buil
```

**Comment by wordhou** [comment]
While digging around in the `gradle.build.kts` files while working on #873, I figured out the configuration settings to change this:

```kotlin
kotlin {
    js {
        nodejs {
            testTask {
                testLogging {
                    exceptionFormat = TestExceptionFormat.FULL // Show full exception when an assertion fails
                }
            }
        }
    }
}
```

This is in the kotlin dsl but I believe it would be the same in Groovy. I'll post a PR shortly.
