### ISSUE TITLE
deprecate ChronoZonedDateTime.toBeLessThan etc.

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#709]
*Platform* (all, jvm, js): jvm
*Extension* (none, kotlin 1.3): none

## Code related feature
```
val now = ZonedDateTime.now()
now.compareTo(now.withZoneSameInstant(ZoneOffset.UTC)) // 1
now.isEqual(now.withZoneSameInstant(ZoneOffset.UTC)) // true
```

We should deprecated the Comparable assertion functions in the context of ZonedDateTime and point to toBeBefore, toBeAfter etc.

See https://github.com/robstoll/atrium-roadmap/issues/50 for further details

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by JordanllHarper** [comment]
Hi I would like to take this on!

**Comment by JordanllHarper** [comment]
@robstoll  I'm just wanting to double check, are you wanting the methods in ' /logic/atrium-logic/src/generated/jvmMain/ch/tutteli/atrium/logic/chronoZonedDateTime.kt ' deprecated? If not, could you point me to the path where I'm needing to deprecate?

**Comment by robstoll** [comment]
@JordanllHarper no, you don't deprecate existing functions, you add new overloads for the existing functions in https://github.com/robstoll/atrium/blob/main/apis/fluent-en_GB/atrium-api-fluent-en_GB/src/commonMain/kotlin/ch/tutteli/atrium/api/fluent/en_GB/comparableExpectations.kt 
for the type ChronoZonedDateTime etc. to the corresponding files in jvmMain (e.g the one you pointed out for ChronoZonedDateTime).
Once you added the overloads, you immediately deprecated them again. We don't intend to remove them again (otherwise there would not be a need to add them in the first place), we will have them as hint for the user as their usage is most likely wrong. See https://github.com/robstoll/atrium/blob/main/apis/fluent-en_GB/atrium-api-fluent-en_GB/src/jvmMain/kotlin/ch/tutteli/atrium/api/fluent/en_GB/bigDecimalExpectations.kt => toEqual. Your deprecated functions should be similar. Also throw a PleaseUseReplacementException and point out that one can use a feature extractor of one desperately want to use toBeGreaterThan and co. On ChronoZonedDateTime and co. I hope you see a bit what you need to do. Otherwise let me know, I can also create to-dos for this issue which will be more or less a step by step instruction

**Comment by JordanllHarper** [comment]
@robstoll I think I understand what you are asking me to do and I'm still working on this!
However, I'm having some issues importing java standard libraries into the comparableExpectations.kt file for both API's. I can't access the java stdlib from the file and am needing some help with this. Apologies for this!

**Comment by robstoll** [comment]
@JordanllHarper no worries, can you please push your changes and create a WIP PR (a draft). It's way easier to help with setting your code
