### ISSUE TITLE
less verbose containsNot reporting and more hints

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#722]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Instead of 
```
expected that subject: [1, 2, 3, 4]        (java.util.Arrays.ArrayList <1234789>)
◆ does not contain: 
  ⚬ an element which: 
      » is greater than: 2        (kotlin.Int <1234789>)
    ✘ ▶ number of such entries: 2
        ◾ is: 0        (kotlin.Int <1234789>)
    ✔ ▶ has at least one element: true
        ◾ is: true
```
We would like to see (similar to `all`)
```
expected that subject: [1, 2, 3, 4]        (java.util.Arrays.ArrayList <1234789>)
◆ does not contain: 
  ⚬ an element which: 
      » is greater than: 2        (kotlin.Int <1234789>)
     ❗❗ following entries were mismatched: 
        ⚬ index 3: 3        (kotlin.Int <1234789>)
        ⚬ index 4: 4        (kotlin.Int <1234789>)
```
Also the 
```
▶ has at least one element: true
        ◾ is: true
```
Should be moved out of `does not contain` (and hence only be shown if failing) in the spirit of #305
Also, we should not re-invent the wheel and use the existing `hasNext` implementation instead of an own `has at least one element`

In case of an empty Iterable, we should still show what the user intended to search for IMO. Something like:
```
expected that subject: []        (kotlin.collections.EmptySet <1837188010>)
◆ has: a next element
  » does not contain:
    ⚬ an element which:
       » is greater than: 2        (kotlin.Int <1234789>)
```
IMO also fine if we show `✘ ▶ number of such entries: ...` in addition if this is simpler (which is the case most likely)

Without this extra information it could be confusing for a user

**Comment by wordhou** [comment]
I'd like to work on this. It looks like the `InAnyOrder(Entries/Values)AssertionCreator` both subclass the `ContainsAssertionCreator` which defines the `createAssertionGroup` method, which creates the `does not contain` assertion group. So would I need to move the `has elements` check up to the `ContainsAssertionCreator` class?

**Comment by robstoll** [comment]
I'll take a look on Wednesday or Thursday. Upfront, replace the custom `has at least one element` with a regular hasNext expectation (see also https://github.com/robstoll/atrium/issues/305). Also, it's fine to do this for all InAnyOrder...

**Comment by robstoll** [comment]
@wordhou Now I remember again, I have already prepared a draft for this issue some time ago which includes the refactoring for InAnyOrderEntriesAssertionCreator and co. I have rebased the work and pushed a new branch notToContain-less-verbose. Yet, there are still open points (I also updated the description of this issue) and it would be nice if you could work on those:
- createHasElementAssertion is still using the own `has at least one element` instead of `_logic.hasNext` and it does not include what the user was searching for as failure hint => I would combine  `_logic.hasNext` with an explanatoryAssertionGroup
- mismatches are not yet reported
- multiple specs are failing => the specs need to be adopted as the structure changed
  - and we should check that the mismatches are reported correctly once implemented
- bc/bbc tests need to be forgiven due to the structure change (I can do this but if you are interested, this needs to be done in settings.gradle.kts)

**Comment by wordhou** [comment]
I'll take a look at your branch this weekend and try and tackle some of these issues. Thanks for the information.
