### ISSUE TITLE
Path.toBeASymbolicLink

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#765]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(path).toBeASymbolicLink()

//instead of

expect(path).feature { f(it::isSymbolicLink)}.toBe(true)
```

Following the things you need to do:

*logic*
- [ ] extend PathAssertions with a function `toBeASymbolicLink` (see isRegularFile as a guideline)
- [ ] implement toBeSymbolicLink in DefaultPathAssertions.kt`

*api-fluent*
- [ ] provide a fun `toBeASymbolicLink` (see isRegularFile as a guideline)
- [ ] add `@since 0.16.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add isSymbolicLink to PathExpectationsSpec in specs-common adopt the spec in api-fluent

*api-infix*
- [ ] provide a fun `toBe` which expect a new pseudo-keyword `aSymbolicLink` (see toBe(aRegularFile)` as a guideline)
- [ ] add `@since 0.16.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add `toBe aSymbolicLink` to PathExpectationsSpec in specs-common adopt the spec in api-fluent
- [ ] add an example to PathAssertionSamples (create the file next to BigDecimalAssertionSamples if it does not exist yet).

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
I vote to name the function `toBeASymbolicLink`.

**Comment by robstoll** [comment]
Good with me, I was considering it as well

**Comment by fimbulwint** [comment]
I'll work on this

**Comment by robstoll** [comment]
@fimbulwint note that I have updated the description. Have fun implementing and let us know in case you need help

**Comment by fimbulwint** [comment]
@robstoll Thanks!

**Comment by fimbulwint** [comment]
@robstoll I'm ready to create a PR, but I don't have permissions to push/create the tracking branch

**Comment by jGleitz** [comment]
@fimbulwint you should for this repository, push the branch to your fork, and then open a Pull Request from your fork. See also [Creating a Pull Request from a Fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by fimbulwint** [comment]
@jGleitz thank you, done that now
