### ISSUE TITLE
Path.toBeAnEmptyDirectory

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#766]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(path).toBeAnEmptyDirectory()

//instead of

expect(path)
  .toBeADirectory()
  .feature("findFirstFile", { Files.list(this).use { it.findFirst() } }) {
    isEmpty()
  }
```

Following the things you need to do:

*logic*
- [ ] extend PathAssertions with a function `toBeEmptyDirectory` (see other functions as a guideline)
- [ ] implement toBeEmptyDirectory in DefaultPathAssertions.kt -- *bonus* use newDirectoryStream instead and list all files as failureHint in case the `iterator.hasNext()`

*api-fluent*
- [ ] provide a fun `toBeAnEmptyDirectory` in a new file called pathExpectations.kt (see for instance isDirectory in pashAssertions.kt as a guideline)
- [ ] add `@since 0.16.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add toBeAnEmptyDirectory to PathExpectationsSpec in specs-common adopt the spec in api-fluent

*api-infix*
- [ ] provide a fun `toBe` which expects `anEmptyDirectory` in a new file called pathExpectations.kt (see `toBe aDirectory` in pathAssertions.kt as a guideline)
- [ ] add `@since 0.16.0` (adapt to current [milestone](https://github.com/robstoll/atrium/milestones)) to KDOC
- [ ] add toBeAnEmptyDirectory to PathExpectationsSpec in specs-common adopt the spec in api-infix

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by Samuellucas97** [comment]
I'll work on this

**Comment by robstoll** [comment]
@Samuellucas97 I have updated the description. Let me know in case you need help

**Comment by robstoll** [comment]
@Samuellucas97 let us know in case you need help

**Comment by mai2412** [comment]
I'd like to try this,

**Comment by robstoll** [comment]
@mai2412 exactly. Use the existing functionality for toBeADirectory so that the reporting in error cases is already advanced

**Comment by mai2412** [comment]
Do you mean isDirectory? I can't find toBeADirectory

**Comment by robstoll** [comment]
@mai2412 yes, isDirectory in DefaultPathAssertions. Sorry
