### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [robstoll/atrium#8]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin. 

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by robstoll** [comment]
Heya, I am using mockito-kotlin but very seldom and I do not have a need for another mocking library at the moment. I might come back if mockito-kotlin has a missing feature which your library provides.

Have a look at Atrium in case you should not know it (it's an assertion library). I plan to integrate mockito-kotlin such that it appears in the report as well (as other assertion functions). 
If you are interested in, we could also integrate your mocking library.

**Comment by oleksiyp** [comment]
I am using assertk, but didnt know about atrium. Surely Im interested in integration. Let me know the details.

**Comment by robstoll** [comment]
I'll come back to you once I am at the point of integrating a mocking library. In the mean time, have a look at Atrium, maybe you get a taste for it ;)
