### ISSUE TITLE
filter out io.kotest runner from RemoveRunnerAtriumError

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#806]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Kotlintest was renamed to kotest a while ago. But we don't filter it. I would keep io.kotlintest but filter io.kotest in addition (check before we check for io.kotlintest)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by mai2412** [comment]
I'd like to work on this.
