### ISSUE TITLE
Create sample project for Atrium + MPP kotlin.test

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#81]
*Platform* (JVM, JS and/or Android): Jvm

## Code-Documentation related feature
It would be nice if we have a working example similar to the one we created for Atrium + mocha (see samples/js/mocha) or Atrium + spek (see samples/jvm/spek) but this time in the context of an multiplatform project (JVM, Android and JS).

The example project shall show how to setup a MPP project + Atrium and contain a simple test written in the common module and one in each platform. 
It is up to you which test runner you use for the specific platforms as long as they are supported by kotlin.test.

This task is a good first issue especially if you intend to set up Atrium in an MPP project

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](http://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by iamshubh** [comment]
Hey assign it to me..

**Comment by bsemexan** [comment]
is this basically dumping all the build configs from the diff ones already there into one?

**Comment by robstoll** [comment]
Not only but yes there is surely a great overlap. It will especially show how one can use Atrium in a test of a common module.

**Comment by bsemexan** [comment]
I went ahead and requested to join Slack as I have questions

**Comment by robstoll** [comment]
@bsemexan I have sent you an invitation for slack to bsemexan@gmail.com as you did not ask your questions. let me know in case it did not work

**Comment by bsemexan** [comment]
this can prob be closed
