### ISSUE TITLE
improve reporting for containsDuplicates

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#813]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
```
expect(listOf(1,2,1,2,3,4,4,4)).containsNoDuplicates()
```
We would like to see the following report instead of the current one:
```
expected that subject: [1, 2, 1, 2, 3, 4, 4, 4]        (java.util.Arrays.ArrayList <114044797>)
    ◆ has not: duplicate elements
      ⚬ index 0: 1          (kotlin.Int <972231853>)
         >> duplicated by index: 2
      ⚬ index 2: 2        (kotlin.Int <525432111>)
          >> duplicated by index: 3
      ⚬ index 5: 4        (kotlin.Int <1676423953>)
          >> duplicated by index: 6, 7
```

TODO:
- adjust DefaultIterablLikeAssertions, use assertionBuilder to create the desired report
- adjust IterableExpectationsSpec accordingly

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by jGleitz** [comment]
If you feel fancy, you can use the proper plural of ‘index’, ‘indeces’ when an element occurs more than twice :)

**Comment by robstoll** [comment]
@wordhou can you please write a comment here so that I can assign you to the issue. Thanks

**Comment by wordhou** [comment]
Hello!
