### ISSUE TITLE
filter for collections

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#82]
*Platform* (JVM, JS and/or Android): all

## Code related feature
Sometimes there are use cases where we would like to assert a certain property for only a few entries of an Iterable in combination with another assertion on the same Iterable. For instance
```
assert(listOf(person1, person2, person3)) {
  all { feature { f (it::age) }.isGreaterThan(18) }
  filter { feature  { f (it::name) }.startsWith("hello") }.containsExactly(person1, person2)
}
```
I think it would make sense to use an identification lambda (usually named assertionCreator with type `Expect<T>.() -> Unit`) for `filter`, similar as in `all` where it is used as identification lambda as well. This way we can use explanatory assertions to describe the assertionCreator in reporting. 
The following would be more attractive: `filter { it.name.startsWith("hello") }` but reporting would not work and one could not reuse other assertion functions.

**Comment by sanatik** [comment]
Meanwhile you can assign this to me.
I'll pick it up after `Iterable.hasNotNext`

**Comment by sanatik** [comment]
@robstoll 
Still not clear for me what exactly the problem is.
Can you add a bit more details, please?

**Comment by robstoll** [comment]
In short, provide a `filter` fun which expects an `assertionCreator` and changes the subject of the assertion (see ExpectImpl.changeSubject.reported...) by filtering entries of an iterable based on whether the assertions the assertionCreator defines hold or not. More will follow tomorrow...

**Comment by robstoll** [comment]
You can use a `CollectingAssertionContainer` (built via `coreFactory.newCollecting...`) and add the assertions to it via `addAssertionsCreatedBy`. This container provides a `getAssertions` method which you can use to retrieve the assertions and check whether they all hold by using `Assertion.holds()`, this way you can use it as predicate of `Iterable.filter`, or in other words filter the current Iterable and change the subject. In reporting we want to see that the iterable was filtered and how. For this you have to use `ExpectImpl.feature` and `ExpectImpl.explanatoryGroup`.

For instance; 
```
expect(listOf(1,2,3,4))
  .filter { isLessThan(3) }
  .containsExactly(-1, 0)
```
Should result in something like the following in reporting
```
expect: List(1, 2, 3, 4)
=> filtered by:                  <--- feature assertion with a RawString.Empty representation
 >> is less than: 3              <--- ExplanatoryAssertionGroup with all collected assertions; could be more than just isLessThan(3)
 * => after filtering: List(2, 3)    <--- feature assertion
     * contains, in order, only:     <-- sub-assertions of the `changeSubject.unreported`
         >> entry 0: 1
             * to be: -1
         >> entry 1: 2
             * to be: 0
          ....
``` 
 Let me know if you require more information. This isn't a `good first issue` anymore (as you can see). Hence it is also perfectly fine if you want to do another good first issue first.

**Comment by sanatik** [comment]
I spent some time this week trying to figure out how to make this work(feel dumb a bit :D), but it's still really unclear for me.
`and add the assertions to it via addAssertionsCreatedBy` what assertions? Sub-assertions? Filter assertion itself?
I did not get the idea of `Assertion.holds()`, what it does exactly?
I have more questions, but I hope those two will drive me into the right direction.
Meanwhile, I see that https://github.com/robstoll/atrium/issues/228 is unassigned and work on that.

**Comment by robstoll** [comment]
Let's start off by an example, makes maybe things easier to illustrate and discuss about:
```
expect(listOf("robert", "sanatik")).filter { startsWith("r") }.containsExactly("robert")
```

`and add the assertions to it via addAssertionsCreatedBy` referred to all assertions defined within the assertionCreator-lambda of filter. So above `{ startsWith("r") }`

`Assertion.holds()` tells you if the assertion holds for the given subject or not. So above `startsWith("r")` holds for `"robert"` but not for `"sanatik"`.

**Comment by robstoll** [comment]
@sanatik please don't spend more time on this one for know, I just realised that this feature is kind of incomplete without the possibility of `or` (see https://github.com/robstoll/atrium-roadmap/issues/47 for more details)

**Comment by robstoll** [comment]
closing this for now, I don't think we get a good cost/benefit here. One can use `feature("filter(...)") { it.filter(...) }` already
