### ISSUE TITLE
replace :wink: and the like with utf-8 smileys

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#86]
## Non-Code related feature
**Is your feature request related to a problem? Please describe.**
Some external websites take the README of github and render it as well. 
Yet, they do not render it as Github does and things like `:wink:` (:wink:) or `:information_source:` (:information_source:) are not rendered. 

**Describe the solution you'd like**
Use UTF-8 symbols instead so that the rendering is also done by the browser
You can use the following table for instance: https://apps.timwhitlock.info/emoji/tables/unicode

**Comment by Frandall** [comment]
Hello, can I work on this?

**Comment by robstoll** [comment]
implemented with 1312f169
