### ISSUE TITLE
rewrite samples to use Kotlin DSL for gradle

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#873]
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Code related feature
Currently, we use groovy in the samples. The Kotlin DSL is still somewhat RC I would say, not everything is smooth but I think it is good enough so that we can already use it in the samples projects

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by wordhou** [comment]
I can give this one a go this week.
