### ISSUE TITLE
add samples for chronoZonedDateTimeExpectations of api-fluent 

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#916]
## Code related feature
With this issue we want to add samples for chronoZonedDateTimeExpectations.kt of api-fluent

Following the things you need to do:
 
*api-fluent*
  - [ ] create ChronoZonedlDateTimeExpectationSamples in apis/fluent-en_GB/atrium-api-fluent-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples
- [ ] add one function per function in chronoZonedDateTimeExpectations.kt (see AnyExpectationSamples) 
  - [ ] suffix the function name for the one which expect a String with `String` e.g. `toBeBeforeString`
  - [ ] *Bonus* show all supported formats for the function expecting a string, mentioning the format as comment
- [ ] refer to the sample in the KDoc of the corresponding function in chronoZonedDateTimeExpectations.kt via `@sample` (check out `toEqual` in anyExpectations.kt to see how you have to refer to the sample)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by dias-wagner** [comment]
I'll work on this
