### ISSUE TITLE
add samples for optionalExpectations of api-fluent

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#917]
## Code related feature
With this issue we want to add samples for optionalExpectations.kt of api-fluent

Following the things you need to do:
 
*api-fluent*
  - [ ] create OptionalExpectationSamples in apis/fluent-en_GB/atrium-api-fluent-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples
- [ ] add one function per function in optionalExpectations.kt (see ListExpectationSamples)
  - [ ] for functions having two overloads where one expects an assertionCreator in addition -- add the suffix `Feature` to the function name of the one not expecting `assertionCreator` (see ListExpectationSamples)
- [ ] refer to the sample in the KDoc of the corresponding function in optionalExpectations.kt via `@sample` (check out `toEqual` in anyExpectations.kt to see how you have to refer to the sample)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by ArcaneOP** [comment]
I'll work on this.But i have no idea ,how this gonna happen.But i want to try this once

**Comment by ArcaneOP** [comment]
can u tell me how to start

**Comment by robstoll** [comment]
See above, the link `your first contribution`

**Comment by ArcaneOP** [comment]
unable to find ListExpectationSamples

**Comment by robstoll** [comment]
Have you forked and cloned the project. You should find it easily via search function of your IDE

**Comment by ArcaneOP** [comment]
yes i forked and cloned it.and also foundListExpectationSamples.Now what to do next..i mean what r the function to be made?

**Comment by robstoll** [comment]
See the description of this issue. it's lore or less a one to one step description. Have you created the OptionalExpectationSamples? Once done you do the next step etc.

**Comment by ArcaneOP** [comment]
Yes i made it ....i will try to do it ....and communicate further...if i
would not able to do that   ...

**Comment by robstoll** [comment]
In case you run into another problem, then create a draft PR please. This way I see what you have already done and thus better understand what next step you try to achieve.

**Comment by robstoll** [comment]
@ArcaneOP do you need help?

**Comment by ArcaneOP** [comment]
I have exams....i will start after 10th..sorry for inconvenience..

**Comment by robstoll** [comment]
No problem at all, no rush, just wanted to be sure you don't have obstacles on the way :slightly_smiling_face:

**Comment by ArcaneOP** [comment]
Thank you! For giving me time🙂

**Comment by timacosta** [comment]
I'll work on this, seems like the previous person's account got deleted. Assign it if OK.

**Comment by robstoll** [comment]
@timacosta do you need help with this?

**Comment by robstoll** [comment]
No rush at all

**Comment by timacosta** [comment]
@robstoll I've started slowly on this one (didn't have any time until now) and I was wondering how complex you expect these samples to be. I was just dealing a bit with the different functions in `optionalSamples.kt` and think I got the point. Just asking before going deeper, cause you can actually do it as complex as possible with Optionals. 

Let me know and clarify if needed, what kind of use cases are you expecting and I can elaborate from there. 

Here is what I did just messing around, simple. 

```kotlin

@Test
    fun toBeEmpty() {
        val empty: String? = null
        val opt = Optional.ofNullable(empty)

        expect(opt).toBeEmpty()
    }

    @Test
    fun toBePresent() {
        val empty: String? = "toBePresent"
        val opt = Optional.ofNullable(empty)

        expect(opt).toBePresent()
    }

```

**Comment by robstoll** [comment]
Rather simple, take a look at other examples. It's always good to have a passing and a failing sample.
