### ISSUE TITLE
add samples for localDateAssertions of api-fluent

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#996]
## Code related feature
With this issue we want to add samples for localDateAssertions.kt of api-fluent

Following the things you need to do:
 
*api-fluent*
- [ ] create LocalDateExpectationSamples in apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples
  - [ ] add one function per function in localDateAssertions.kt (see AnyExpectationSamples)
  - [ ] refer to the sample in the KDoc of the corresponding function in localDateAssertions via `@sample` (check out `toEqual` in anyExpectations.kt to see how you have to refer to the sample)

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

**Comment by rhushikesh** [comment]
Hi @robstoll, 

I have raised a PR for issue https://github.com/robstoll/atrium/issues/997. Samples required for localDateAssertions are pretty much in line with localDateTimeAssertions. If you are okay with PR of that issue, I can pick this issue up as well and raise required PR. 

Thank you

**Comment by robstoll** [comment]
@rhushikesh great that you have that much time :+1: There is also #998 which is very similar. In case you have even more time, then add a comment there as well and I assign it to you

**Comment by rhushikesh** [comment]
HI @robstoll, 

I have raised PR for this issue https://github.com/robstoll/atrium/pull/1006. I have accommodated changes you had suggested for [localDateTimeAssertions PR](https://github.com/robstoll/atrium/pull/1005) as well. 

Please have a look and let me know our thoughts.
